### ISSUE TITLE
ASP MVC 6 dnxcore 5 support

### ISSUE THREAD

**Issue by StefTheNetGuy** [jmelosegui/GooglemapMvc#100]
Hi, I'm trying to integrate your package in a new MVC 6 website but I get a bunch of errors and the root cause is your package not being compatible with DNX Core v5.0
Are there plans to have a release supporting DNXCore v5.0? 
Thanks!

**Comment by jmelosegui** [comment]
I knew this was coming :). And yes this is in my to do list.

**Comment by jmelosegui** [comment]
I will keep this open to track it down.

**Comment by jmelosegui** [comment]
I have updated the code for .net6.
