### ISSUE TITLE
Plotting Multiple Polygons

### ISSUE THREAD

**Issue by khalome** [jmelosegui/GooglemapMvc#104]
Is there a way to plot multiple "closed" polygons? Something similar to the example below but the problem with this code is it plots one huge polygon that doesn't look correct. I suppose the loop would come before adding the points but not sure what syntax to use.
```
@{
    Html.GoogleMap()
           .Name("map")
           .Height(500)
           .Center(c => c.Address("KC"))
           .Zoom(4)
           .Polygons(pf => pf.Add()
                .Points(ptn =>
                    {
                        foreach (var item in Model)
                        {
                            for (int i = 0; i < item.geometry.coordinates.Count() - 1; i++)
			                {
			                    ptn.Add(item.geometry.coordinates[i][0], item.geometry.coordinates[i][1]);
			                }
                       }
                    }
                )
                .FillColor(System.Drawing.Color.Red)
                .StrokeColor(System.Drawing.Color.DarkRed)
           ).Render();
}
```

**Comment by khalome** [comment]
I guess I should clarify. In my model Model.features.geometry.coordinates is a List<List<List<List<double>>>>. So iterating through the collection would look like 

for (int i = 0; i < item.geometry.coordinates.Count() - 1; i++)
{
ptn.Add(item.geometry.coordinates[0][0][i][0], item.geometry.coordinates[0][0][i][1]);
}

**Comment by khalome** [comment]
I did get this to work but there might be a more elegant way.

@{
    Html.GoogleMap()
           .Name("map")
           .Height(500)
           .Center(c => c.Address("KC"))
           .Zoom(4)
           .Polygons(pf => {
               foreach (var item in Model)
	            {
                    pf.Add()
                        .Points(ptn =>
                            {
                                for (int i = 0; i < item.geometry.coordinates[0][0].Count() - 1; i++)
                                {
                                    var t1 = item.geometry.coordinates[0][0][i][0];
                                    var t2 = item.geometry.coordinates[0][0][i][1];
                                    ptn.Add(t2, t1);
                                }
                            })
                            .FillColor(System.Drawing.Color.Red)
                            .StrokeColor(System.Drawing.Color.DarkRed);
	                    }
                   }
                )
           .Render();

**Comment by jmelosegui** [comment]
Nice you can make it work.
Regarding
>a more elegant way

You could replace the `foreach (var item in Model)` by `Databinding` see [this](http://www.jmelosegui.com/map/Shapes/DataBindingToModel) form more info.

Regarding

>In my model Model.features.geometry.coordinates contains multiple lists.

I would rather improve the data structure so that the access to the coordinate `latitude` and `longitude` could be done through properties of some kind of object instead of indexes in a collection (but that is up to you).

Let me know if you have more questions.
