### ISSUE TITLE
Marker Clusterer Icons missing

### ISSUE THREAD

**Issue by btidoug** [jmelosegui/GooglemapMvc#106]
The marker clusterer icons are missing from the map.  Debug shows 
http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/images/m3.png is not found.
![clusterer](https://cloud.githubusercontent.com/assets/6748163/15964284/a6427a64-2ee5-11e6-8aef-73ede3dcac47.png)

**Comment by jmelosegui** [comment]
Yes, this is a known issue (see [googlemaps/js-marker-clusterer/#59](https://github.com/googlemaps/js-marker-clusterer/issues/59)). 
This control allows you to specify your own image source though.
See [this](http://www.jmelosegui.com/map/marker/MarkerClustering) sample and change the style to "stackoverflow"
