### ISSUE TITLE
Can't find drawing library

### ISSUE THREAD

**Issue by khalome** [jmelosegui/GooglemapMvc#109]
I see the drawing library is easily added in the examples at http://www.jmelosegui.com/map/Libraries/Drawing. However in my solution Libraries is missing. I reinstalled the package but still don't see it available in the code. In the packages config it says I have version "0.8.0.0" installed. Am I missing something?

**Comment by jmelosegui** [comment]
Hi @khalome 

That feature is not included in the version 0.8.0.0. Please read the  [self-service-releases](https://github.com/jmelosegui/GooglemapMvc#self-service-releases) and let me know if that works for you.

**Comment by khalome** [comment]
Thanks, I added a config file and installed PM> Install-Package Jmelosegui.Mvc.Googlemap -Pre. I can see in the packages.config a reference to version "0.8.16-beta-gd2b2689432" but intellisense never brings up Libraries() when creating a map. If I compile and run anyways the map never renders. I am not sure if I am creating the nuget.config properly or it's in the right place.

**Comment by gabriele-v** [comment]
Same here, also after adding self-service-releases:
`Added package 'Jmelosegui.Mvc.Googlemap.0.8.16-beta-gd2b2689432'`

But Libraries() still missing..
Any ideas?
