### ISSUE TITLE
Google Map in New MVC .Net Core

### ISSUE THREAD

**Issue by maxitimes** [jmelosegui/GooglemapMvc#111]
Hi there, i have been using your Googlemapmvc in the older version of MVC successfully.  However i have recently started converting my projects into the new .Net Core MVC 6 and found your nuget package is not compatible.

Will you be updating it? Please

**Comment by anti-matter** [comment]
Definitely would like this support as well.

**Comment by jmelosegui** [comment]
I have updated the code for .net6.

Please try the new version and reopen this issue if it still exists.
