### ISSUE TITLE
MissingKeyMapError

### ISSUE THREAD

**Issue by nyeinchanoo** [jmelosegui/GooglemapMvc#112]
Hi Sir,

When I browse my map website using public IP, I got MissingKeyMapError. How can we add Key using Jmelosegui API. Please advise

**Comment by Ruban1989** [comment]
I get the same error. Is there any way to overcome it. I dont find any way to enter the key.

**Comment by sjafarianm** [comment]
you should add a script to your page like 
`<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDY0kkhgyurspkJiTPVd2U7aTOAwjighc9ySH6oHxOIYM&sensor=false"></script>`
you can get this key by registering your website in some URL provided by google. you can find it by googling it.

**Comment by jmelosegui** [comment]
I think there is a helper method for that. The code should be something like this:

```
@(Html.GoogleMap()
          .Name("map")
          .ApiKey("YourApiKeyHere"))
```

Please, could you confirm this method solve your scenario?

**Comment by ASDK1** [comment]
you should generate an api key for your web application

**Comment by nyeinchanoo** [comment]
After adding API key as following,

@(Html.GoogleMap()
          .Name("map")
          .ApiKey("YourApiKeyHere"))

it works.

Thank you very much

**Comment by Ruban1989** [comment]
Thanks. Excellent Work.

**Comment by SteveWhite383** [comment]
Thanks for your speedy reply and top class solution!

**Comment by nguyenhoangdat** [comment]
Hi, after Add APIKey and publish to iis then error 438 : Object doesn't support property or method 'GoogleMap'
