### ISSUE TITLE
Polyline function is not working in IIS

### ISSUE THREAD

**Issue by nyeinchanoo** [jmelosegui/GooglemapMvc#113]
I followed #94 to get polyline function. I can draw polyline in development time. But I hosted web app to IIS. I got "500 internal error". If I remove polyline function, it work in IIS. Can you advise me?

**Comment by jmelosegui** [comment]
Well, for this I will need the steps to reproduce, or some code sample showing the issue. 
Can you share the actual error message behind the "500 internal error".

**Comment by nyeinchanoo** [comment]
Sorry I don't have any other error message. I can check it in browser.
browser show "500 internal Error".

**Comment by jmelosegui** [comment]
:eyes:

**Comment by jmelosegui** [comment]
I have updated the code for .net6.

Feel free to reopen this if it is still an issue for you
