### ISSUE TITLE
Libraries property is not included in the nuget package?

### ISSUE THREAD

**Issue by ramiassi** [jmelosegui/GooglemapMvc#114]
Hello,
I was trying to use the GooglemapMvc package in my .net MVC application. I wanted to include a searchbox on the map just like the example you have on [http://www.jmelosegui.com/map/Libraries/SearchBox](http://www.jmelosegui.com/map/Libraries/SearchBox)

The compiler kept showing the error message : GoogleMapBuilder does not contain a definition for 'Libraries'. I tested different versions of the package using the nuget package manager but nothing fixed this error.

**Comment by jmelosegui** [comment]
See this #109
