### ISSUE TITLE
Map in RenderAction is not visible

### ISSUE THREAD

**Issue by ogousseau** [jmelosegui/GooglemapMvc#115]
Hi,

Merci for your job.
I have a problem, when i call this page : 

```
@using Jmelosegui.Mvc.GoogleMap

<div style='width: 100%; height: 300px;'>
    @{ 
        Html.GoogleMap()
        .Name("mapmodule")
        .Height(300)
        .StreetViewControlVisible(false)
        .Center(c => c.Latitude(48.695).Longitude(1.855))
        .Zoom(9)
        .Markers(marker =>
        {
            marker.Add()
                .Latitude(48.695)
                .Longitude(1.855)
                .Title("toto");
        })
        .Render();
    }
</div>
```

from a another page : 

```
@{ Html.RenderAction("MapModule", "Module", new { id = Model.Id }); }
```

the map doesn't appear and not code is generated in HTML

Where i wrong ?

Merci pour votre aide.
Olivier.

**Comment by jmelosegui** [comment]
do you get any javascript error (in the browser javascript console)?

**Comment by ogousseau** [comment]
Hi, sorry i haven't any errors in browser or console.

**Comment by jmelosegui** [comment]
Did you followed the instructions on [https://github.com/jmelosegui/GooglemapMvc#install](https://github.com/jmelosegui/GooglemapMvc#install). Especially the following code at the end of the page?
```
@section scripts
{
    @(Html.GoogleMap().ScriptRegistrar())
}
```
Could you create a sample project reproducing this error (here in github) so I can clone it and try to help?

**Comment by jmelosegui** [comment]
:eyes:

**Comment by jmelosegui** [comment]
Feel free to reopen is this is still relevant for you
