### ISSUE TITLE
Scroll Wheel

### ISSUE THREAD

**Issue by jhallam3** [jmelosegui/GooglemapMvc#116]
Hi Scroll wheel cannot be found in the Html.GoogleMap()

as shown in the picture attached, Im using version 0.8.0

![screen shot 2016-08-06 at 13 45 09](https://cloud.githubusercontent.com/assets/5174328/17480749/4e27fc18-5d71-11e6-9e6f-0dcf124857a4.png)

**Comment by jmelosegui** [comment]
I don't think it is on the official NuGet version, but you can add the AppVeyor feed and get the latest nightly following [this](https://github.com/jmelosegui/GooglemapMvc#self-service-releases) steps.
