### ISSUE TITLE
Implementing autocomplete without map 

### ISSUE THREAD

**Issue by Zev19** [jmelosegui/GooglemapMvc#117]
Hi,

Great work on this control. I do have a question though, is it possible to implement just the searchbox with autocomplete implemented without having to create a google map?

An example like this? https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform

Very new to GitHub, so I apologise if I am posting this incorrectly.

**Comment by jmelosegui** [comment]
I think that is out of the scope of this project.
