### ISSUE TITLE
Realtime updates

### ISSUE THREAD

**Issue by papyr** [jmelosegui/GooglemapMvc#118]
Hi @jmelosegui nice work :+1:  

I have been playing with this sample [here](http://www.jmelosegui.com/map/marker/DataBindingToModel) can you please share me some guidance on how to show realtime updates while truck moving. I have tried with signalR 2

Also, how to check bounding box, car/truck is out of box area.

thanks
Papi

**Comment by jmelosegui** [comment]
SignalR should work but that is an interaction between the server and the javascript on the client and has less to do with this `MVC` control.

Regarding the bounding box check out the [FitToMarkersBounds](http://www.jmelosegui.com/map/marker/FitToMarkersBounds) sample.

Thanks for your feedback.
