### ISSUE TITLE
4.5.2 fails and Nuget does not update

### ISSUE THREAD

**Issue by winecraft** [jmelosegui/GooglemapMvc#121]
Hello, I am using VS 2015 (also tried 2013), I'm getting errors when I target 4.5.2 _(BTW you have 2 different versions currently, 4.5 and 4.5.1)_

![image](https://cloud.githubusercontent.com/assets/13067681/18527966/f462b6d2-7a94-11e6-9c78-04517bb137b6.png)

![image](https://cloud.githubusercontent.com/assets/13067681/18528120/a413d28c-7a95-11e6-8a1f-b4fe47549e44.png)

**Comment by jmelosegui** [comment]
In order to build the solution through Visual Studio you need to install [NoProj](https://visualstudiogallery.msdn.microsoft.com/fbe9b9b8-34ae-47b5-a751-cb71a16f7e96).
I think that will solve your issue. Please try it and let me know.

**Comment by jmelosegui** [comment]
I also updated the [documentation](https://github.com/jmelosegui/GooglemapMvc#contributing-prerequisites)  to reflect those changes.
