### ISSUE TITLE
Build fails against 4.5.1 and VS 2015 dev

### ISSUE THREAD

**Issue by papyr** [jmelosegui/GooglemapMvc#122]
Hi @jmelosegui with the latest, the build is now failing for me. I am not sure if its visual studio or the plugin.

I noticed you made some changes and followed your documentation on the addition of noproj - did this break my build? please help me understand, do I need to build this as a nuget project?

thanks
Papi

**Comment by jmelosegui** [comment]
Could you post the error message or part of the build log??

**Comment by papyr** [comment]
hope this helps, I was able to get it working _mostly_ there are many superficial/cascading errors, I suspect 4 main issues, I was able to resolve 3

- [ ] first pertaining to referencing other projects working on nuproj, 
- [x] second pertaining to upgrading your sln and proj files to the current VS 2015 service pack 3.x file formats as of last weeks release
- [x] third, is the lack of reference to 4.5.2 _I resolved this and below I added the code where I changed it._
- [x] fourth, its faster with the latest newtonsoft serializer, but it will not upgrade to that. I suspected a dependency issue... I could not fix the nerbank nuget, but I fixed the JSON serializers by looking at the 2015 dependencies int he projects, very simple with build order.

If you see this below, means your project meta-files have changed format and location...

> Severity	Code	Description	Project	File	Line	Suppression State
> _Error		Your project is not referencing the ".NETFramework,Version=v4.5.2" framework.	Jmelosegui.Mvc.GoogleMap.Examples_	

		

After a little digging and diff with the previous versions, I found inside the project meta-data files you had 2 versions 4.5 and 4.5.1. This error message was suppressed since VS 2015 sp1, and 2 had non-verbose setting.

In the upgrade there are two project.json files you need those fixed

I changed this ` "frameworks": {
    "net451": {}
  },` to ` "frameworks": {
    "net452": {}
  },`

hope it helps :+1:  

can you add the nuproj to the default download here, in my case it would have helped with the trouble shooting over the last 2 days

**Comment by winecraft** [comment]
@papyr glad I follow your posts, this really helped me!

**Comment by papyr** [comment]
Since I was able to fix most of it, I am going to close it. thanks
