### ISSUE TITLE
VS 2015 compile and build issues

### ISSUE THREAD

**Issue by amhik** [jmelosegui/GooglemapMvc#123]
Dear Sir, my build is fail with this version in visual studio 2015, it used to work till last year, but now its looking for other parts. Can you please check and upload a building version, or would I need to include some more to resolve dependencies

Many thanks
Amy

**Comment by jmelosegui** [comment]
Could you share your build log?

[here](https://ci.appveyor.com/project/jmelosegui/googlemapmvc) you can find the latest build log from master branch working properly.

**Comment by papyr** [comment]
I was also running into something similar, then when I read the other issues, I found [this](https://github.com/jmelosegui/GooglemapMvc/issues/121)  make sure you include [this](https://visualstudiogallery.msdn.microsoft.com/fbe9b9b8-34ae-47b5-a751-cb71a16f7e96)

**Comment by papyr** [comment]
build issues in VS 2017, can you please check and update

**Comment by jmelosegui** [comment]
there is a work in progress for 2017 in the [netcore](https://github.com/jmelosegui/GooglemapMvc/tree/netcore) branch

**Comment by jmelosegui** [comment]
I have updated the code for .net6.

Please try the new version and reopen this issue if it still exists.
