### ISSUE TITLE
Scripts render issue

### ISSUE THREAD

**Issue by s-amani** [jmelosegui/GooglemapMvc#126]
Hi
I have a problem with rendering related scripts with map, As I follow your tutorials, I added `@(Html.GoogleMap().ScriptRegistrar())` to end of my View. But it seems it doesn't render scripts to page. There is no error to help me to understand where is the problem. I also tried pre-release version, But I still having same problem.

**Comment by jmelosegui** [comment]
Could you shared the code you are using (maybe a small project here on GitHub so I can look at it and try to help)?

**Comment by jmelosegui** [comment]
Feel free to reopen this if it is still an issue for you
