### ISSUE TITLE
Low bandwidth connection, offline and caching of maps

### ISSUE THREAD

**Issue by papyr** [jmelosegui/GooglemapMvc#127]
Hello, in countries where the connection speeds are no the best... or disconnected scenarios,

can you please add a way to turnon cache mode for the maps.

So on the control something like `[Cache-enabled-Map-True]` attribute could be added.

thanks

**Comment by jmelosegui** [comment]
What is exactly what you want to cache?
What do  you mean by?

>cache mode for the maps 

If you want to cache the map tiles, that function has to exist on google map APIs, and I think (although I am not a lawyer) it is explicitly prohibited here ([http://maps.google.com/help/terms_maps.html](http://maps.google.com/help/terms_maps.html)) on section 2.c.

There is also an interesting discussion on the subject [here](https://github.com/heldersepu/gmapcatcher/issues/210).

**Comment by papyr** [comment]
Ohh common man!!   Web apps & devs are constantly caching fonts, images, code, audio, video, don't you think they would all be sued by caching!!!

Here [you go](https://www.google.com/search?q=google+maps+caching&ie=utf-8&oe=utf-8)
 and this [one is actually directly from google](https://support.google.com/maps/answer/6291838?co=GENIE.Platform%3DAndroid&hl=en) on how to setup the maps. We just need someway to enable it... trust me, you will thanks me when the speed quadruples!


If your search the terms, there is no caching mentioned. Without getting too facetious, its simple, we need to buffer and cache the user content to reserve up the call. 

For e.g. 90% of the work done by a team, like construction is all around the same area of construction, so it makes a lot of sense to server up the same with a simple object, or memcachedb, I can code and merge it in if you could show me where to handle the caching/buffering for the maps.
