### ISSUE TITLE
ScrollWheel

### ISSUE THREAD

**Issue by ogousseau** [jmelosegui/GooglemapMvc#129]
Hi,

How can i use ScrollWheel propertie in my code ?

i try this :
@using Jmelosegui.Mvc.GoogleMap

@(
    Html.GoogleMap()
        .Name("map")
        .ApiKey("my code")
        .Height(450)
        .StreetViewControlVisible(false)
        .Center(c => c.Latitude(@ViewBag.lat) .Longitude(@ViewBag.lon))
        .MarkerEvents(events => events.OnMarkerClick("markerClick"))
        .Zoom(9)
        .ScrollWheel(false)

But it's wrong.

Thanks for your help.

Olivier.

**Comment by jmelosegui** [comment]
What is wrong? Could you give me more details?

Meantime you can see the feature in action [here](http://www.jmelosegui.com/map/basic/UIControls).

Let me know if that helps.

**Comment by ogousseau** [comment]
Hi,

I'm working on a new projet and i have the same problem :
[cid:image003.jpg@01D2799F.98C3DEA0]

I use the 0.8.16 version.
[cid:image004.png@01D2799F.98C3DEA0]



Can you help me ?

Merci beaucoup.
Olivier.

De : Olivier GOUSSEAU
Envoyé : samedi 14 janvier 2017 11:21
À : jmelosegui/GooglemapMvc <reply@reply.github.com>
Objet : RE: [jmelosegui/GooglemapMvc] ScrollWheel (#129)

Bonjour,

Do you have find the solution ?

Do you want more informations ?

Thank you for your help.

Olivier.

De : Olivier GOUSSEAU
Envoyé : mercredi 11 janvier 2017 19:17
À : 'jmelosegui/GooglemapMvc' <reply@reply.github.com>
Objet : RE: [jmelosegui/GooglemapMvc] ScrollWheel (#129)

Hi,

Think for your response.

This code doesn't compile :

@using Jmelosegui.Mvc.GoogleMap

@(
    Html.GoogleMap()
        .Name("map")
        .ApiKey("my key")
==>        .ScrollWheel(false)
        .Height(450)
        .StreetViewControlVisible(false)
        .Center(c => c.Latitude(@ViewBag.lat) .Longitude(@ViewBag.lon))
        .MarkerEvents(events => events.OnMarkerClick("markerClick"))
        .Zoom(9)
        .BindTo<SensMyCity.Models.CustomerGeoZone, Marker>
        (Model, mappings => mappings.For<SensMyCity.Models.CustomerGeoZone>
            (
                binding => binding.ItemDataBound
                    (
                        (marker, obj) =>
                        {
                            marker.Id = obj.id;
                            marker.Latitude = obj.latitude;
                            marker.Longitude = obj.longitude;
                            marker.Title = obj.name;
                        }
                    )
            )
        )

    )

<script type="text/javascript">
    function markerClick(args) {
        if (args.eventName === 'click') {
            var link = "/Sensor/Index?_from=SensMyCity&" + args.id;
            window.location = link;
        }
    }
</script>
@section scripts
{
    @(Html.GoogleMap().ScriptRegistrar())
}

The compiler said me he doesn't find the property ScrollWheel

Do you want a screen copy of the error ?

I used the last version of your control.

Think for your help :)

Merci.
Olivier.

De : Juan Manuel Elosegui [mailto:notifications@github.com]
Envoyé : mercredi 11 janvier 2017 18:52
À : jmelosegui/GooglemapMvc <GooglemapMvc@noreply.github.com<mailto:GooglemapMvc@noreply.github.com>>
Cc : Olivier GOUSSEAU <ogousseau@2gsi.fr<mailto:ogousseau@2gsi.fr>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Objet : Re: [jmelosegui/GooglemapMvc] ScrollWheel (#129)


What is wrong? Could you give me more details?

Meantime you can see the feature in action here<http://www.jmelosegui.com/map/basic/UIControls>.

Let me know if that helps.

-

**Comment by jmelosegui** [comment]
Have you guys followed the [Self-service releases](https://github.com/jmelosegui/GooglemapMvc#self-service-releases) instruction for the nightly build? 
I think that feature is not in the package published on nuget.org.

**Comment by ogousseau** [comment]
Yes, I do that !

Have you see my screen copy with error ?

My assembly is on 0.8.0.0, it’s good ?
Path : <projet>\packages\Jmelosegui.Mvc.Googlemap.0.8.16-beta-gd2b2689432\lib\net45\Jmelosegui.Mvc.GoogleMap.dll    good ?

Thanks for your help ☺

Olivier.

De : Juan Manuel Elosegui [mailto:notifications@github.com]
Envoyé : lundi 30 janvier 2017 14:29
À : jmelosegui/GooglemapMvc <GooglemapMvc@noreply.github.com>
Cc : Olivier GOUSSEAU <ogousseau@2gsi.fr>; Author <author@noreply.github.com>
Objet : Re: [jmelosegui/GooglemapMvc] ScrollWheel (#129)


Have you guys followed the Self-service releases<https://github.com/jmelosegui/GooglemapMvc#self-service-releases> instruction for the nightly build?
I think that feature is not in the package published on nuget.org.

**Comment by ogousseau** [comment]
Bonjour,

I’m sorry to dismiss you a new time but do you have find problem ? Do you wamt more informations ?

Merci beaucoup.
Olivier.

De : Olivier GOUSSEAU
Envoyé : lundi 30 janvier 2017 14:40
À : 'jmelosegui/GooglemapMvc' <reply@reply.github.com>; jmelosegui/GooglemapMvc <GooglemapMvc@noreply.github.com>
Cc : Author <author@noreply.github.com>
Objet : RE: [jmelosegui/GooglemapMvc] ScrollWheel (#129)

Yes, I do that !

Have you see my screen copy with error ?

My assembly is on 0.8.0.0, it’s good ?
Path : <projet>\packages\Jmelosegui.Mvc.Googlemap.0.8.16-beta-gd2b2689432\lib\net45\Jmelosegui.Mvc.GoogleMap.dll    good ?

Thanks for your help ☺

Olivier.

De : Juan Manuel Elosegui [mailto:notifications@github.com]
Envoyé : lundi 30 janvier 2017 14:29
À : jmelosegui/GooglemapMvc <GooglemapMvc@noreply.github.com<mailto:GooglemapMvc@noreply.github.com>>
Cc : Olivier GOUSSEAU <ogousseau@2gsi.fr<mailto:ogousseau@2gsi.fr>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Objet : Re: [jmelosegui/GooglemapMvc] ScrollWheel (#129)


Have you guys followed the Self-service releases<https://github.com/jmelosegui/GooglemapMvc#self-service-releases> instruction for the nightly build?
I think that feature is not in the package published on nuget.org.

**Comment by jmelosegui** [comment]
The code is updated to .net6.

Feel free to reopen this issue if it is still relevant for you.
