### ISSUE TITLE
Having problem with displaying map in MVC 5

### ISSUE THREAD

**Issue by vedos** [jmelosegui/GooglemapMvc#131]
Can you help me I am having trouble displaying simple map in MVC 5 using Areas it won't render anything I only get blank page and there is no errors????

**Comment by jmelosegui** [comment]
Sorry for the late response. Could you provide some sample (maybe a project here on github) so I can clone it and tty to help?

**Comment by jmelosegui** [comment]
Feel free to reopen this if it is still an issue for you
