### ISSUE TITLE
How to make auto complete address?

### ISSUE THREAD

**Issue by Bonvoath** [jmelosegui/GooglemapMvc#137]
Hi. Is there any way to make auto complete address?
![screenshot](https://cloud.githubusercontent.com/assets/20592892/23490186/67696068-ff29-11e6-8f7a-cf849b4a5e99.png)

**Comment by jmelosegui** [comment]
Have you tried [this](http://www.jmelosegui.com/map/Libraries/SearchBox)?

**Comment by Bonvoath** [comment]
Thank for your reply. I still got error with Libraries method.
I use Jmelosegui.Mvc.Googlemap.0.8.0.0.



Thank you for you help.

**Comment by jmelosegui** [comment]
please follow [this](https://github.com/jmelosegui/GooglemapMvc#self-service-releases) instructions to get a version containing that feature.

**Comment by Bonvoath** [comment]
Thank you again for your help. Could you help check this souce code?​
 MvcWithGoogelMap.rar
<https://drive.google.com/file/d/0B2R9KbgqPdBHMFd4V3ZpMXZDRGc/view?usp=drive_web>
​
