### ISSUE TITLE
Any way to get Map JS object for doing manual javascript on it?

### ISSUE THREAD

**Issue by Pugglewuggle** [jmelosegui/GooglemapMvc#139]
Is there any way to get the Google Maps JS object of a map output by this library? I need to run some code from the Google JS API on the map in addition to what's done by this library.

**Comment by jmelosegui** [comment]
Could you try to see if  [this](http://www.jmelosegui.com/map/basic/ClientEvents) sample helps?
Specifically, the `OnMapLoaded` where you can get a reference to the map object in javascript.

**Comment by Pugglewuggle** [comment]
This works great, thank you.
