### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by btidoug** [jmelosegui/GooglemapMvc#14]
Where do you set the Google map API key?

**Comment by btidoug** [comment]
Ok - I found how to add the api key ... but now still getting an error where it is building the googlmaps link to the map.
![error](https://cloud.githubusercontent.com/assets/6748163/6063505/d1687e84-ad25-11e4-8497-aa96ba9e1b58.png)

**Comment by btidoug** [comment]
```c#
                    @(Html.GoogleMap()
                        .Name("map")
                        .Height(300)
                        .ApiKey("use my actual code")
                    )

**Comment by jmelosegui** [comment]
Is your ApiKey an "alphanumeric only" value or do you have any special character in your Key?

Are you following the [google specifications](https://developers.google.com/maps/documentation/javascript/tutorial#api_key) to obtain an api key?

**Comment by btidoug** [comment]
This is weird.  I create a plain index view from controller like example and it displays a map with or without a api key.  When I copy all the pieces to where it is supposed to "live", I get that error. 

So, it has to be with my page.  I am using DataTable to show a table of waypoints.  When you select a row, it makes a ajax call to a different controller action that returns some more details about the waypoint.  This is where I want to show the map.  Must be something with the html coming back from the ajax call to controller.
