### ISSUE TITLE
Add Infowindow to markers that are databound from model

### ISSUE THREAD

**Issue by Pugglewuggle** [jmelosegui/GooglemapMvc#140]
What following this example, I want to add an infowindow to each marker. 

http://www.jmelosegui.com/map/marker/DataBindingToModel

How can I do this? The .Content property of a Window doesn't have a setter and there are no constructors which allow me to pass in a string for the content when doing this:
 ```
binding => binding.ItemDataBound
					(
						(marker, obj) =>
						{
							marker.Latitude = obj.Points[0].Latitude;
							marker.Longitude = obj.Points[0].Longitude;
							marker.Icon = new MarkerImage("~/Content/icons/icon.png", new Size(20, 20), new Point(0, 0), new Point(0, 20));
							**marker.Window = new InfoWindow(marker);**
							**marker.Window.Content = "My Content";**
							marker.Title = "Chicken";
							marker.Clickable = true;
						})
```

**Comment by jmelosegui** [comment]
Can you go to [http://www.jmelosegui.com/map/marker/DataBindingToModel](http://www.jmelosegui.com/map/marker/DataBindingToModel) and click on the view tab and see if that code help you?

**Comment by Pugglewuggle** [comment]
Ah, I didn't see you use initialization lists. Thanks. I'll let you know if there's anything else.
