### ISSUE TITLE
trailing, fading dots

### ISSUE THREAD

**Issue by papyr** [jmelosegui/GooglemapMvc#142]
Hi how do I show trailing fading dots of a jogger?

**Comment by jmelosegui** [comment]
I don't understand your question (English is not my primary language). Could you provide more details or maybe a working sample from the google map api site?

**Comment by papyr** [comment]
Hi, basically display dots to [form a trial ](http://bit.ly/2n7SPJy)

The newer dots will be brighter, older dots will be lighter and completely disappear on the map, so it fades away. 

Only recent will show, that way the map is clean and not over crowded with lines. Hope this helps

**Comment by papyr** [comment]
Hi, this might help - [it has the code](http://bit.ly/2oE5p49)

**Comment by jmelosegui** [comment]
Not sure if this is specific to this component. Atm, it is not supported. 
I am sure you could use multiple features from google maps.

1. A combination of data bindings with custom images for the markers depending on some sort of date.
2. Also maybe you could consider using the [heat map sample](https://www.jmelosegui.com/map/Layers/Heatmap) not exactly the same but some approximation.
