### ISSUE TITLE
does no show the map

### ISSUE THREAD

**Issue by Lduran97** [jmelosegui/GooglemapMvc#144]
I have a problem in my app mvc 5

I install the pack but does not show the map

![e1](https://cloud.githubusercontent.com/assets/28150502/25534616/4b00c938-2c02-11e7-99e4-d6be35d2262d.PNG)

![err](https://cloud.githubusercontent.com/assets/28150502/25534557/2021ca1e-2c02-11e7-9673-33fc6112c57f.PNG)

**Comment by Batelkan** [comment]
put .Render() at the end,

@(
        Html.GoogleMap()
            .Name("map")
            .Height(300)
            .Center(c => c.Latitude(23.140971656573335)
                          .Longitude(-82.39435493946075))
            .Markers(m => m.Add().Title("Hello World!"))
).Render();

work for me

**Comment by jmelosegui** [comment]
I have updated the code for .net6.

Please try the new version and reopen this issue if it still exists.
