### ISSUE TITLE
i have an error when i try to use drawing 

### ISSUE THREAD

**Issue by fsdamra** [jmelosegui/GooglemapMvc#149]
Severity	Code	Description	Project	File	Line	Suppression State
Error CS1061 'MapBuilder' does not contain a definition for 'Libraries' and no extension method 'Libraries' accepting a first argument of type 'MapBuilder' could be found (are you missing a using directive or an assembly reference?)	

and this is the code i took it from the sample :
@(Html.GoogleMap()
        .Name("map")
        .Height(500)
        .Libraries(libraries)
        .ClientEvents(events => events.OnMapLoaded("mapEvent"))
    )

im using visual studio 2015

**Comment by jmelosegui** [comment]
I have updated the code for .net6.

Please try the new version and reopen this issue if it still exists.
