### ISSUE TITLE
js error with infowindow

### ISSUE THREAD

**Issue by danielnp20** [jmelosegui/GooglemapMvc#15]
Hi all, 

I'm trying to use the GoogleMapMVC project with an info window, but when i clicked on the marker i got the js error "Uncaught TypeError: Cannot read property 'cloneNode' of null"

I want to know if anyone had the same issue and how can i fix it

thanks a lot for your help

**Comment by jmelosegui** [comment]
Can you add a code sample (the less code the better) to reproduce the error?

**Comment by danielnp20** [comment]
Thks i found the problem and was mine. I used the word section and it has conflict

**Comment by danielnp20** [comment]
Hi, I suposed the problem was with a js variable named "section" but I was wrong. I uploaded the problem on the following url: http://www.amp-tg.com/Home/Contact

And this is the code i have:

    var poslat = 4.6882219073128795;
    var poslong = -74.03698925249249;
    var mapzoom = 12;
    var mapicon ="~/Images/Site/amp-icon.png";
    var mapsize = new Size(22, 22);
    var mappoint = new Point(0, 0);
    var mapanchor = new Point(12, 18);

                            Html.GoogleMap()
                                .Name("map")
                                .Zoom(mapzoom)
                                .Culture(CultureInfo.GetCultureInfo("es-CO"))
                                .Center(c => c.Latitude(poslat).Longitude(poslong))
                                .Markers
                                (
                                    marker => marker.Add()
                                        .Latitude(poslat)
                                        .Longitude(poslong)
                                        .Title("AMP Tecnología y Gestión S.A.S")
                                        .Icon(mapicon, mapsize, mappoint, mapanchor)
                                        .Draggable(false)
                                        .Window
                                        (
                                            window => window.Add()
                                                @*.MaxWidth(200)
                                                .zIndex(3)
                                                .Content
                                                (
                                                    @<text>
                                                        <div id="content">
                                                            <h2>AMP Tecnología y Gestión S.A.S</h2>
                                                            <div id="bodyContent">
                                                                <p>
                                                                    <b>Dirección: </b> Carrera 20 # 178 - 45 Ofic. 303
                                                                    <i><b>direccion: </b></i> officially <i>Ciudad deLa Habana</i>,
                                                                </p>
                                                            </div>
                                                        </div>
                                                    </text>
                                                )*@
                                        )
                                )
                                .Render();

**Comment by jmelosegui** [comment]
I think you problem is that you set the id of the map container to "map" and the GoogleMapMVC 
control Name to "map"

    <div id="map">
        @(Html.GoogleMap().Name("map"))        
    </div>

Change one of them and you should be good to go.

**Comment by danielnp20** [comment]
thanks!! .. that solves the issue!
