### ISSUE TITLE
Polyline issue, 

### ISSUE THREAD

**Issue by manocv** [jmelosegui/GooglemapMvc#156]
Hi

I am using a beta version of API to draw a polyline, no error or warning shows, but cannot draw the polyline, just the marker has been placed based on Lat Lng. 

Using VS2017, so I tried Polygon and it is working fine, so the same function working in VS2013.

Please advice how to find the issue, urgent.

Thanks in advance # #

**Comment by jmelosegui** [comment]
Code migrated to .net6. Try the new version and reopen this issue if it still exists.
