### ISSUE TITLE
OnIdle event not correct

### ISSUE THREAD

**Issue by jvillaro** [jmelosegui/GooglemapMvc#16]
Hi Juan,

I was trying to do something based on the "idle" event but it didn't work at first. Trying out your events demo I tested event per event and got the idle event to fire using "OnMapHeadingChanged" instead of the "OnMapIdle".
Have you noticed this? Am I going crazy?

Thanks in advance.
Jose.

**Comment by jmelosegui** [comment]
Hi Jose, 

You are right. There is a wrong mapping to that event when the class GoogleMapClientEvents is serialized. I just fix that so you can test it. Next week I will create a new nuget package that include this fix among others.

Thanks for your feedback.

**Comment by jvillaro** [comment]
Hi Juan,

I’ll thank you for your efforts!
