### ISSUE TITLE
how to group marker into one player

### ISSUE THREAD

**Issue by tranhoangtam** [jmelosegui/GooglemapMvc#161]
how to group marker into one player
like https://leafletjs.com/examples/layers-control/

**Comment by jmelosegui** [comment]
Not sure what do you mean by `player`.

assuming you want to cluster markers, this sample could help.

https://www.jmelosegui.com/map/marker/MarkerClustering

**Comment by jmelosegui** [comment]
Closing this issue until more information is provided

**Comment by VjDriven** [comment]
He means one layer on the map
