### ISSUE TITLE
How to view map by an address instead of by latitude and longitude?

### ISSUE THREAD

**Issue by minista1** [jmelosegui/GooglemapMvc#17]
HI! I would like to use your project. But I would like to be able to <b>load addresses</b> not longitude and latitude. I tried to add the address parameter. But I could get it to work.  I know is possible. Do you get any suggestion on how I can implement that? Thank you very much.

**Comment by jmelosegui** [comment]
Geocoding service is something I will start working soon.
Unfortunately GoogleMapMvc doesn't have that feature yet.

Thanks for your feedback.

**Comment by minista1** [comment]
HI! i used this library to find the Latitude and longitude: Google Maps Web Services API wrapper for .NET
https://github.com/maximn/google-maps

I found that too: https://github.com/Adconsulting/ADC.GMaps

You can use them to see how they get the Latitude and longitude with  the address.
Thank you for your library! :-)

**Comment by jmelosegui** [comment]
Hi @minista1 

Just added a new sample showing the [geocoding services](http://www.jmelosegui.com/map/Services/Geocoding). 
Please let me know if this is what you are expecting.

**Comment by minista1** [comment]
HI! Yes, this what i was expected. Thank you very much. Now there is no need to get the longitude and latude if we get only the address.

Good job!

**Comment by sistemasat** [comment]
Hi jmelosegui.
I have the address on the map getting by text and I need the coordinates (latitude and longitude).
Is it possible?

Thanks a lots .

Gustavo
