### ISSUE TITLE
Multiple marker selection

### ISSUE THREAD

**Issue by btidoug** [jmelosegui/GooglemapMvc#19]
Love that I found this control!!  Makes my life a lot easier!

Is there a possibility of adding a new function - allow user to select multiple markers from the google map and return list to controller?  I have see some examples of attempts on the web for ctrl+click or for drawing a "shape" and then selecting the markers.  Don't know how to add those examples to this control.

Thanks!

**Comment by jmelosegui** [comment]
Selecting marker is something that happens on client side. 
Currently you can subscribe to client event only on the map object. 
Handle events on markers is something i need to implement. 
I will leave this issue open until the feature is ready.

Thanks for your feedback.

**Comment by btidoug** [comment]
Can the id of the map be identified with JQuery and have client events added with View script until the feature is implemented?

**Comment by jmelosegui** [comment]
@btidoug you can subcribe to the "OnMapLoaded" client event. See [this](http://www.jmelosegui.com/map/basic/ClientEvents) example for more info.

```
 @(Html.GoogleMap()
            .Name("map")
            .Height(420)
            .ClientEvents(events => events               
                .OnMapLoaded("mapLoadedHandler")
            ))
```

then in the view you will get a reference to the map object passed in the arguments  

```
<script type="text/javascript">
    function mapLoadedHandler(args) {
            var map = args.map;
            //do something with the map object

        }
</script>
```
*Note: map is a reference to the [google map](https://developers.google.com/maps/documentation/javascript/reference#Map) object.*

That object does not have any method like map.getMarkers(). So with the current version you cannot add the click event handler to the markers because you **do not** have a reference to those markers.

So keep tuned. I will try to add "Client Events" to the markers over the week end.

Thanks for your feedback

**Comment by btidoug** [comment]
I will wait for your updates over the weekend.  Thank you very much!  I
can't believe I tried doing this all by hand!

Basically, I have a waypoint tracking program where the user can select
checkboxes of a bunch of waypoints from a table and they will "live" appear
as markers on the map.  This all works great so far.  Now, I want users to
be able to then select the actual marker(s) on the map and be able to make
collective changes to the underlying datasource waypoints for things like
renaming, choosing a common lake, change icon, etc.

If you control could allow me to select marker(s), somehow visually show
the user they are selected (like change icon, color, or fill a textarea
control on screen), and then be able to send the id(s) of the selected
marker(s) back to the controller so I can process and persist the changes
back to the database, THAT WOULD BE AMAZING!  I can add the actual db id of
the waypoint to the marker and "hide" it somewhere so I can then extract it
back at the controller.

Thank you!  Do you have a donate page?

-Doug

**Comment by jmelosegui** [comment]
Hi @btidoug,

Just closed issue #21 which should be enought to fullfil your request.

Note that the new functionality is on the dev branch. You can see it in action [here](http://www.jmelosegui.com/map/marker/ClientEvents)

When you have a chance please download the latest version of the sample project and let me know what you think.

**Comment by btidoug** [comment]
Looks awesome!  

Couple of questions:
1. With the "left click" event on the marker now, does that affect the info window original functionality of the map itself?
2.  Is there a way to also grab a key control on left click?  Ex. Can I detect if ctrl+left click was used?

Thanks!

**Comment by jmelosegui** [comment]
1. On a marker, if you add a window and also add an event handler to the click event. Both events will occur: the control will call the function you set in the "OnMarkerClick" property of the control and the Info Window will pop up too.

2. I added a MouseEvent property to the client event arguments of the google marker. Now you can check key press along with the click events.

```
@(Html.GoogleMap()
    .Name("map")
    .Height(420)
    .Markers(m =>
    {
        m.Add().Id("UniqueId-1")
            .Title("Hello World!")
            .Longitude(-82)
            .Latitude(23);
    })
    .MarkerEvents(events => events.OnMarkerClick("markerClick"))
)

<script type="text/javascript">
    function markerClick(args) {       
		if (args.eventName === 'click' && args.mouseEvent.ctrlKey === true) {
            alert("You clicked the marker with id =" + args.id + " while pressing the ctrl key");
        }    
    }
</script>
```

Also I update the [sample](http://www.jmelosegui.com/map/marker/ClientEvents) project to reflect those changes.

**Comment by btidoug** [comment]
I love you...in a code guru kind of way!

**Comment by btidoug** [comment]
Any chance of a nuget package update?

**Comment by jmelosegui** [comment]
I need to add some improvement on InfoWindows serialization. 
I think I will push the next version over the weekend

**Comment by jmelosegui** [comment]
Hi @btidoug 

Bad news :(  I was testing the marker click event and just realize the "internal" MouseEvent property is not always filled out by google. So the "hack" I used to check the ctrl key pressed will not  work. 

Let me see if I can figure out a work around.

**Comment by btidoug** [comment]
Is it specifically the control key? I can use whatever key...shift, alt,
etc.
