### ISSUE TITLE
Map centering

### ISSUE THREAD

**Issue by btidoug** [jmelosegui/GooglemapMvc#20]
Is there a way to center a map based on the "average" of the markers that will be placed on it?

**Comment by jmelosegui** [comment]
Well this is something you can accomplish with the current version.

in your controller before passing the marker collection to the view you can calculate the average longitude and latitude and set the map center using those values

```
    public partial class MarkerController
    {
       public ActionResult DataBindingToModel()
        {
           var markerCollection = DataContext.GetMarkers();
           var center = CalculateAverageCenter(markerCollection);
           var model = new MyModel
           {
                 mapCenter = center,
                 markerks = markerCollection
           }
            
            return View(model);
        }
    }
```

then in the view just set the center and the marker collection. for more info look [this](http://www.jmelosegui.com/map/marker/DataBindingToModel) example.

**Comment by btidoug** [comment]
Is the CalculateAverageCenter function part of your control or is that just
a place holder for me to go make a function to find the center?

**Comment by jmelosegui** [comment]
It is something you have to implement.

**Comment by btidoug** [comment]
Ok ... no biggie just checking.

Thank You!
