### ISSUE TITLE
Setting map height to 100% of the parent container

### ISSUE THREAD

**Issue by ritdaw** [jmelosegui/GooglemapMvc#25]
The map width currently has a default of 100%, can the same be done for the height?

**Comment by jmelosegui** [comment]
hi @ritdaw, 

Now, if you set the map height to 0 or you do not set it at all, the map will get the height from its parent.

You can see this feature in action [here](http://www.jmelosegui.com/map/basic)

Thanks for your feedback

**Comment by ritdaw** [comment]
Brilliant thanks!

**Comment by ritdaw** [comment]
Any idea when the latest will be deployed to Nuget?

**Comment by jmelosegui** [comment]
This weekend

**Comment by ritdaw** [comment]
Great thanks.
