### ISSUE TITLE
Multiple marker selection - repost

### ISSUE THREAD

**Issue by btidoug** [jmelosegui/GooglemapMvc#27]
Any update on the issue you were having with the "ctrl" key processing for allowing user to use ctrl-click to select multiple markers?

**Comment by jmelosegui** [comment]
@btidoug, as you can see [here](https://developers.google.com/maps/documentation/javascript/reference#MouseEvent) google map mouse event does not provide any info about  key pressed during a mouse event. That is why I have none easy way to provide that information.

I will try to hack up a work around but I won't include the solution in any release until I  have something I can rely on.
