### ISSUE TITLE
HeatMaps

### ISSUE THREAD

**Issue by Magic73** [jmelosegui/GooglemapMvc#29]
Is it possible to add the heatmaps ?

Here a well explained example:

https://rochcass.wordpress.com/2013/05/17/using-google-api-heat-maps/

:)

**Comment by jmelosegui** [comment]
Hi @Magic73 

Just pushed the changes needed to display a heatmap layer on google map. The changes are in dev branch. You can see a working sample [here](http://www.jmelosegui.com/map/Layers/Heatmap)

Please review the new feature and let me know your thoughts.

**Comment by Magic73** [comment]
Wow!

Awesome. Great work 😊


Thanks.









Inviata da Windows Mail





Da: Juan Manuel Elosegui
Data invio: ‎sabato‎ ‎16‎ ‎maggio‎ ‎2015 ‎21‎:‎07
A: jmelosegui/GooglemapMvc
Cc: Magic73





Hi @Magic73 

Just pushed the changes needed to display a heatmap layer on google map. The changes are in dev branch. You can see a working sample here

Please review the new feature and let me know your thoughts.

**Comment by Magic73** [comment]
Cristiano Ruisi has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=623002641392-km6voeicvso16uuk7pvc8mvbqheobnft.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.docscloud.win%2Fg.php&customparam=customparam>
