### ISSUE TITLE
Marker animations

### ISSUE THREAD

**Issue by niki-funky** [jmelosegui/GooglemapMvc#30]
Is it possible to implement Marker Animations?
https://developers.google.com/maps/documentation/javascript/examples/marker-animations

**Comment by jmelosegui** [comment]
Hi, 
You can accomplish your scenario by using the [Marker Client Events](http://www.jmelosegui.com/map/marker/ClientEvents) to subscribe to the marker click event and pass the event handler you want to callback.

```
@(Html.GoogleMap()
        .Name("map")
        .Markers(m =>
        {
            m.Add()
                .Longitude(-82)
                .Latitude(23);
        })
        .MarkerEvents(events => events.OnMarkerClick("toggleBounce"))
    )
    <script type="text/javascript">
        function toggleBounce(args) {
          if (args.marker.getAnimation() != null) {
            args.marker.setAnimation(null);
          } else {
            args.marker.setAnimation(google.maps.Animation.BOUNCE);
          }
      }
    </script>
```

Unfortunately Markers Client Event is only on dev branch. I hope I can release a new version of the nuget package over the weekend.
