### ISSUE TITLE
KML

### ISSUE THREAD

**Issue by pjsimon4321** [jmelosegui/GooglemapMvc#31]
Is there a way to display a KML in the current version of the application?  If not, I may start working on it and can contribute my changes, but before I did that, I wanted to see if it already existed somewhere in the code.

I am looking and I don't see it...

Thanks!

**Comment by jmelosegui** [comment]
Hi, 

No, the current version does not have that feature. Contributions are welcome.

**Comment by jmelosegui** [comment]
Hi @pjsimon4321,

Just pushed a set of changes to allow displaying a Kml layer through GoogleMap control for Asp.Net MVC. To see the details please review [this](http://www.jmelosegui.com/map/Layers/Kml) sample.

The changes are in dev branch. Please review them and let me know your thoughts.

**Comment by jpgutton** [comment]
Hi @jmelosegui,

This is fantastic ! I was starting looking for KML layer, I have 2 issues, when I build from the new source two build errors are found (mapobject.cs - line 13 and infowindow.cs - line 29), when "fixing" it I have then another error : 

Unhandled exception at line 37, column 59140 in http://localhost:33868/0a0795d1180b4483bbadcda9aeed7056/browserLink
0x800a139e - JavaScript runtime error: Syntax error, unrecognized expression: unsupported pseudo: plusone

it still work but I keep getting the error every time I click on something (note that I run the test on http://localhost:24576).

Any help will be greatly appreciated !

**Comment by jmelosegui** [comment]
Hi @jpgutton, 

See following answer, that works for me.

[http://stackoverflow.com/questions/20244048/javascript-errors-when-debugging-in-visual-studio-2013?answertab=oldest#answer-22213274](http://stackoverflow.com/questions/20244048/javascript-errors-when-debugging-in-visual-studio-2013?answertab=oldest#answer-22213274)
