### ISSUE TITLE
Centering + Zooming Map based on Markers

### ISSUE THREAD

**Issue by ritdaw** [jmelosegui/GooglemapMvc#32]
Hi,

Is it currently possible to center the map based on the markers defined? i.e. if I had 20 markers throughout the United Kingdom could I center the map and zoom in as far as possible but still fit all of the markers on screen?

Thanks

**Comment by jmelosegui** [comment]
Hi @ritdaw 
I think you are looking for the "Fit map bounds to markers coordinates" feature. That feature is already implemented in the control. Please review the [FitToMarkersBounds](http://localhost/Jmelosegui.Mvc.Googlemap.Examples/marker/FitToMarkersBounds) sample for more info.

BTW there is a new release of the nuget package ([v0.6.0.0]()), so just update your project with the latest version and you will be able to use all the new features.

**Comment by ritdaw** [comment]
Thanks, sorry I missed that somehow.
