### ISSUE TITLE
Question about multiple instances

### ISSUE THREAD

**Issue by net4u** [jmelosegui/GooglemapMvc#33]
Hi,

After playing for several days with the control, with success, today I implemented it in a _partialView approach.
 After finding a way for successful dealing with multiple models in a single view (via rendering partial views), I made two _PartialViews that I render inside a regular view. The issue that I don't know how to deal with is that the first partial render ok and also display the map, the second don't display the map (but I suppose that somehow it works partially because if I inspect the page the markers are pulled from model and are in their divs. Also I noticed at console level error(s) that say that "You have included the Google Maps API multiple times on this page. This may cause unexpected errors." Since I only referenced google map script only in _Layout I suppose that something is looping.
 Also I noticed that I must add :
@section scripts
 {
 @(Html.GoogleMap().ScriptRegistrar())
 }
 also in _partialViews that include the control and also in the view that render them. (I can suppose that from here comes the loop of referencing google map script?!)
 Also I noticed that inspecting the view, the divs that hold each map have both id="map" and I suppose that is not ok.

Also I noticed if I stop render the first _Partial view that include a map, the second becomes visible

**Comment by jmelosegui** [comment]
Hi @net4u,

I just added a new sample to show how to render multiple map instances in the same page.
For more info review the following [link](http://www.jmelosegui.com/map/basic/Multimap)

The new feature is in the dev branch. When you have a chance, please, download the latest version and let me know your thougths.

**Comment by net4u** [comment]
Hi,

Thank you. Update via NuGet?

**Comment by jmelosegui** [comment]
I am working on more features for the next version.
Maybe in a couple of weeks.
