### ISSUE TITLE
_PartialView

### ISSUE THREAD

**Issue by niki-funky** [jmelosegui/GooglemapMvc#34]
Hi Juan ,
You have done great job. 
I'm having trouble using your google maps helper in PartialView. Is it possible? If yes can you show some example. Thank you.

**Comment by net4u** [comment]
Hi,

I used with success in partial view as follows:

@using System.Drawing
@using Jmelosegui.Mvc.Googlemap
@using Jmelosegui.Mvc.Googlemap.Overlays
@using JobShop.Models
@using JobShop.Extensions

@*@model JobShop.Models.IndexVM*@

@model IEnumerable<JobShop.Models.Candidates>

<div class="effect8">
    @{ Html.GoogleMap().Name("map_c")

                          .FitToMarkersBounds(true)

                          //.MarkersGeocoding(true)

                          .Height(500)
                          .Center(c => c.Latitude(44.43551)
                                        .Longitude(26.102568))
                          .BindTo<Candidates, Marker>
                          (Model, mappings => mappings.For<JobShop.Models.Candidates>
                                  (
                                      binding => binding.ItemDataBound
                                      (
                                          (marker, Candidates) =>
                                          {
                                              marker.Latitude = Candidates.Latitudine;
                                              marker.Longitude = Candidates.Longitudine;
                                              marker.Title = Candidates.Titlu;

                                           //marker.Icon = new MarkerImage(String.Format("~/Assets/Images/flags/{0}", Candidates.ImageSRC)
                                           //                                , new Size(18, 12)
                                           //                                , new Point(0, 0)
                                           //                                , new Point(0, 12));

                                           marker.Window = new InfoWindow(marker)
                                              {
                                                  Template =
                                                                  {
                                                            Content = () => ViewContext.Writer.Write(Candidates.Titlu)
                                                                  }
                                              };
                                          }
                                      )
                                  )
                          ).Render();
    }
</div>

<hr />

**Comment by jmelosegui** [comment]
Hi @niki-funky,

Could you describe in more detail the issue you are facing?

I just create a new mvc application, then a partial with named "_MapViewer.cshtml" with the following content

```
@(Html.GoogleMap()
      .Name("map")
      .Height(300)
 )
```
then inside the Index.cshtml view I added this

```
@Html.Partial("_MapViewer")
```
then at the very end of that page this
```
@section scripts
{
    @(Html.GoogleMap().ScriptRegistrar())
}
```
I also added the following line to the web.config file inside the Views folder.
```
<add namespace="Jmelosegui.Mvc.Googlemap"/>
```
with this I don't need to add the **_using_** inside every page.

When I run the newly created web site I see the map rendering in the page.

**Comment by niki-funky** [comment]
Hi,
I'm using async Task<ActionResult> to get the model and to render the Partial view with the map. And then comes the problem. When I call the Action from the View - google map is not working.

**Comment by jmelosegui** [comment]
How do you call the partial view?
Are you doing an ajax request using any client side framework such as jQuery?

**Comment by niki-funky** [comment]
Hi Juan,
yes I'm doing ajax request using JQuery. I see that Google js is not loading. I will look at your control to see how is ScriptRegistrar() implemented .

**Comment by Magic73** [comment]
Put the scripts registrar inside the master page which contains the PartialView:

@section scripts
{
    @(Html.GoogleMap().ScriptRegistrar())
}

it should works :)

**Comment by jmelosegui** [comment]
Hi @niki-funky 

I just added a few changes to allow rendering the map using an ajax call. 

Please review the following [example](http://www.jmelosegui.com/map/basic/AjaxPartialView) and let me know what do you think.

Thank for your feedback.

**Comment by niki-funky** [comment]
Working great. Thank you.
