### ISSUE TITLE
Width/Height 100% - fix

### ISSUE THREAD

**Issue by Magic73** [jmelosegui/GooglemapMvc#36]
I found an issue… I’m using the source code version of the package, instead of the NuGet one.
there’s a mistake on a GoogleMapBuilder which prvent to use the % width/height size.

GoogleMapBuilder, Build function.
actual version:
```
if (Component.Width != 0)
{
 content.Css("width", Component.Width + "px");
}
else
{
    content.Css("width", "100%");
}
```
fixed one:
```
if (Component.Width != 0)
{
 content.Css("width", Component.Width + "px");
}
//else
//{
//    content.Css("width", "100%");
//}

if (Component.Height != 0)
{
 content.Css("height", Component.Height + "px");
}
```

an also in GoogleMap class, inside the WriteInitializationScript I changed the width/height set to:
```
 if (Height > 0)
 objectWriter.Append("height", Height);
else
 objectWriter.Append("height", "100%");
 
if (Width > 0)
 objectWriter.Append("width", Width);
else
 objectWriter.Append("width", "100%");
```
so that if width/height are not set, the default behaviour is to use the 100% size.

**Comment by jmelosegui** [comment]
About the _GoogleMapBuilder_ type, I cannot find a version with the else branch associated with the component width.
 
In regard with the _GoogleMap_ type. There is no need to append those values (_height_ and _width_) to the serialized object during the _ScriptRegistrar_ output. Those values are used to create the html tags for the control. So I will prevent google map control to serialize those values and link the changeset to this issue so you can review it.

Thanks for your feedback and let me know if you see something else.

**Comment by Magic73** [comment]
"About the GoogleMapBuilder type, I cannot find a version with the else branch associated with the component width."

My fault.  there's the else branch to be commented on the Height. lines 47-50

30         public IHtmlNode Build() 
31         { 
32             var content = new HtmlElement("div") 
33                 .AddClass("googlemap") 
34                 .Attribute("id", Component.Id); 
35                 //TODO: Implementar 
36                 //.Attributes(Component.HtmlAttributes); 
37 
 38             if (Component.Width != 0) 
39             { 
40                 content.Css("width", Component.Width + "px"); 
41             } 
42 
 43             if (Component.Height != 0) 
44             { 
45                 content.Css("height", Component.Height + "px"); 
46             } 
47             else 
48             { 
49                 content.Css("height", "100%"); 
50             } 
51 
 52             return content; 
53         }
