### ISSUE TITLE
Custom class

### ISSUE THREAD

**Issue by Magic73** [jmelosegui/GooglemapMvc#37]
I added a new property “Class” to the GoogleMap class, in order to be able to override the default one.

inside the GoogleMap class:

 public string Class { get; set; }

then inside the GoogleMapBuilder class:

public GoogleMapBuilder Class(string className)
{
 if (className == null) throw new ArgumentNullException("class");
 Component.Class = className;
 return this;
}

and inside the Build function:
var content = new HtmlElement("div")
       .AddClass(String.IsNullOrEmpty(Component.Class) ? "googlemap" : Component.Class)
       .Attribute("id", Component.Id);

**Comment by jmelosegui** [comment]
With the current version it is really easy to customize the googlemap container by including styles in your css targeting the googlemap class the control provide.

I don't really see the need to add the "Class" helper method you are suggesting.
Could you please point me out with some scenarios where the current implementation is not enough

Thank for your feedback.
