### ISSUE TITLE
Global access to the GoogleMap object

### ISSUE THREAD

**Issue by Magic73** [jmelosegui/GooglemapMvc#39]
I don't know it there's a better way in order to access to the GoogleMap internal object.

I edited the jmelosegui.googlemaps.js :

at the top of the file I defined a global var: 

var gMapObject;

then I initilized this var where you create the Map object:

gMapObject = new google.maps.Map(this.getElement(), innerOptions);
this.GMap = gMapObject;

in case, would you like to point me how may I access to the Map object outisde the jmelosegui ?

**Comment by jmelosegui** [comment]
With the current version you can subscribe to the **OnMapLoaded** client event of the control and inside the event handler you can receive the instance of the google map object through the argurments.

In the view write something like

```
@(Html.GoogleMap()
            .Name("map")
            .ClientEvents(events => events                
                .OnMapLoaded("mapLoadedHandler")
            ))
```
Then the following
```javascript
@section Scripts{
    <script type="text/javascript">
        function mapLoadedHandler(args) {
            var map = args.map;
            //TODO: Use the map object
        }
    </script>
}
```
For more info about client event see the following [sample](http://www.jmelosegui.com/map/basic/ClientEvents)

**Comment by Magic73** [comment]
I need to access to the Gmap object outside the main page. from an external javascript (which doesn't know anithing about jmelosegui...)
