### ISSUE TITLE
Show info window on right click

### ISSUE THREAD

**Issue by btidoug** [jmelosegui/GooglemapMvc#41]
Can the marker client events be redirected so a right click on a marker will show the info window instead of a left click?

**Comment by jmelosegui** [comment]
Hi @btidoug 

Now the InfoWindow object has a property **OpenOnRightClick** to allow open the windows on either click or rightclick base on that property.

I also updated the infowindow [sample](http://www.jmelosegui.com/map/marker/InfoWindow). Please review the sample and let me know what do you think.

All the changes are on dev branch.
