### ISSUE TITLE
Does not work in i.e

### ISSUE THREAD

**Issue by kwb332** [jmelosegui/GooglemapMvc#42]
Maps dont display in i.e or modzilla.  Works in Chrome.  I am using MVC 3.

Thank you,

Kwame

**Comment by jmelosegui** [comment]
Hi @kwb332,

Could you point out some code sample reproducing the error ? 
Is there any error on IE or Firefox developer console?
Could you point out any sample from the [demo site](http://www.jmelosegui.com/map) with that issue?

Thanks for your feedback.
