### ISSUE TITLE
Binding to Model & Multiple Markers

### ISSUE THREAD

**Issue by righter86** [jmelosegui/GooglemapMvc#43]
Hi Juan, I'm having a little difficulty getting any markers to display. What I'm needing to do is to show markers on the map from my model. Any advice? Right now the map shows up with nothing in it.

MODEL:
```
namespace Course_Runners.Models
{
    public class CoursesContext : DbContext
    {
        public CoursesContext(): base("DefaultConnection")
        { }
        public DbSet<Course> Courses { get; set; }
    }

   [Table("Courses")]
    public class Course
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CourseId { get; set; }

        [Required]
        [Display(Name = "Course Name: ")]
        public string CourseName { get; set; }

        [Display(Name = "Category: ")]
        public string Category { get; set; }

        [Display(Name = "Latitude: ")]
        public decimal? Latitude { get; set; }

        [Display(Name = "Longitude: ")]
        public decimal? Longitude { get; set; }
    }
}
```
CONTROLLER:
```
        public ActionResult CourseMap()
        {
            var viewModel =   db.Courses.Where(pd => pd.Hide == 0);
            
            return View(viewModel);
        }
```
VIEW:
```
@{    Html.GoogleMap()
        .Name("map")
        .Height(600)
        .Center(c => c.Latitude(40).Longitude(-98))
        .Zoom(4)
        .BindTo<Course_Runners.Models.Course, Marker>
        (Model, mappings => mappings.For<Course_Runners.Models.Course>
            (
                binding => binding.ItemDataBound
                    (
                        (marker, regionInfo) =>
                        {
                            marker.Latitude = (double?) regionInfo.Latitude;
                            marker.Longitude = (double?) regionInfo.Longitude;
                            marker.Title = regionInfo.CourseName;
                            marker.Window = new InfoWindow(marker)
                            {
                                Template =
                                {
                                    Content = () => ViewContext.Writer.Write(regionInfo.Category)
                                }
                            };
                        }
                    )
            )
        ).Render();
}
```

**Comment by jmelosegui** [comment]
Hi @righter86,

I can't see any thing wrong with your code above. 
Are you sure you do have items in the viewmodel when you pass it to the view?
Can you create a simple repository here on github reproducing the error so I can clone it and try to figure out the issue?

**Comment by righter86** [comment]
I think I found an issue with my linq query & got it showing now. But now I have another question.

With the InfoWindow for each marker. Right now I have a link for each marker but I also want to display a couple more rows of information but can't figure out how to format the code:

....
@{
    Html.GoogleMap()
        .Name("map")
        .Height(600)
        .Center(c => c.Latitude(40).Longitude(-98))
        .Zoom(4)
        .BindTo<Course_Runners.Models.Course, Marker>
        (Model, mappings => mappings.For<Course_Runners.Models.Course>
            (
                binding => binding.ItemDataBound
                    (
                        (marker, regionInfo) =>
                        {
                            marker.Latitude = (double?) regionInfo.Latitude;
                            marker.Longitude = (double?) regionInfo.Longitude;
                            marker.Title = regionInfo.CourseName;
                            marker.Window = new InfoWindow(marker)
                            {
                                Template =
                                {
                                    Content = () => ViewContext.Writer.Write(
                                        Html.ActionLink(regionInfo.CourseName, "Details", new { controller = "Courses", id = regionInfo.CourseId }))

                                  ///Want to add something like regionInfo.Category here underneath
                                  the link

                                }
                            };
                        }
                    )
            )
        ).Render();
}
....

**Comment by jmelosegui** [comment]
Please review the following [sample](http://www.jmelosegui.com/map/marker/InfoWindow)

**Comment by righter86** [comment]
I tried that example & plugged it in & tried editing it but I couldn't add anything after my Html.ActionLink.
