### ISSUE TITLE
Error when used in a Detail View

### ISSUE THREAD

**Issue by net4u** [jmelosegui/GooglemapMvc#44]
Hi
I use for a while the control in a Index view, but I can't make it working in a Detail view (where I want to see only the current marker for given record that I show as detail).
The list view is like:

    @using System.Drawing
    @using Jmelosegui.Mvc.Googlemap
    @using Jmelosegui.Mvc.Googlemap.Overlays
    @using JobShop.Models
    @using JobShop.Extensions
    @using PagedList.Mvc;
    @model PagedList.IPagedList<JobShop.Models.Candidate>
    @{
    ViewBag.Title = "Available Candidates";
    }

                                    <div class="effect8">
                                        @{ Html.GoogleMap()
                                             .Name("map")
                                             .FitToMarkersBounds(true)
                                             .Height(500)
                                             .Center(c => c.Latitude(44.43551)
                                             .Longitude(26.102568))
                                             .BindTo<JobShop.Models.Candidate, Marker>
                                             (Model, mappings => mappings.For<JobShop.Models.Candidate>
                                             (
                                             binding => binding.ItemDataBound
                                             (
                                             (marker, Candidate) =>
                                             {
                                             marker.Latitude = Candidate.Latitudine;
                                             marker.Longitude = Candidate.Longitudine;
                                             marker.Title = Candidate.Title;
                                             marker.Window = new InfoWindow(marker)
                                             {Template = {Content = () => ViewContext.Writer.Write(Candidate.Title)}};
                                             }
                                             )
                                             )
                                             ).Render();
                                        }
                                    </div>
    @*other content on page as list*@
    @section scripts
    {
    @(Html.GoogleMap().ScriptRegistrar())
    }

and the detail view is like:

    @using System.Drawing
    @using Jmelosegui.Mvc.Googlemap
    @using Jmelosegui.Mvc.Googlemap.Overlays
    @using JobShop.Models
    @using JobShop.Extensions
    @model JobShop.Models.Candidate

    @{
    ViewBag.Title = "Candidate Details";
    }

                            <div class="effect8">
                                @{ Html.GoogleMap()
                                     .Name("map")
                                     .FitToMarkersBounds(true)
                                     .Height(500)
                                     .Center(c => c.Latitude(44.43551)
                                     .Longitude(26.102568))
                                     .BindTo<JobShop.Models.Candidate, Marker>
                                     (Model, mappings => mappings.For<JobShop.Models.Candidate>
                                     (
                                        binding => binding.ItemDataBound
                                     (
                                        (marker, Candidate) =>
                                        {
                                        marker.Latitude = Candidate.Latitudine;
                                        marker.Longitude = Candidate.Longitudine;
                                        marker.Title = Candidate.Title;
                                        marker.Window = new InfoWindow(marker)
                                        {Template = {Content = () => ViewContext.Writer.Write(Candidate.Title)}};
                                        }
                                        )
                                        )
                                        ).Render();
                                }
                            </div>
    @*other content on page as details*@   
    @section scripts
    {
    @(Html.GoogleMap().ScriptRegistrar())
    }

In detail view I have this error:
Line 34:                                      (Model, mappings => mappings.For<JobShop.Models.Candidate>
Detailed compiler output:
~\Views\Candidates\Details.cshtml(34,38): error CS1502: The best overloaded method match for 'Jmelosegui.Mvc.Googlemap.GoogleMapBuilder.BindTo<JobShop.Models.Candidate,Jmelosegui.Mvc.Googlemap.Overlays.Marker>(System.Collections.Generic.IEnumerable<JobShop.Models.Candidate>, System.Action<Jmelosegui.Mvc.Googlemap.Overlays.OverlayBindingFactory<Jmelosegui.Mvc.Googlemap.Overlays.Marker>>)' has some invalid arguments

~\Views\Candidates\Details.cshtml(34,39): error CS1503: Argument 1: cannot convert from 'JobShop.Models.Candidate' to 'System.Collections.Generic.IEnumerable<JobShop.Models.Candidate>'
What can I do in this situation?

**Comment by jmelosegui** [comment]
Hi @net4u 

If you are trying to show only one marker on the map you don't need the "Bind to model" feature at all.

Please see the following [sample](http://www.jmelosegui.com/map/marker/InfoWindow) for more info.
