### ISSUE TITLE
Display content in the modal

### ISSUE THREAD

**Issue by mythros** [jmelosegui/GooglemapMvc#46]
Hello, thanks for the nice work. 

In the modal on the marker, how do I enter or change the content in that modal? 

After reading your custom events, I can see demo where, a user clicking action -> highlights that event, but **getting information there from the Controller or View does not seem to be easy (or perhaps there is something very custom you're doing)**. 

Am I missing something? Can you please break this down into simpler steps for us...

**Comment by jmelosegui** [comment]
If by "modal" you mean the marker info window. You should follow the following [sample](http://www.jmelosegui.com/map/marker/InfoWindow)

If you want to know how to databind the info window content to some datasource, you should follow this [sample](http://www.jmelosegui.com/map/marker/DataBindingToModel)
