### ISSUE TITLE
Move all Defaults and Keys to initialize function.

### ISSUE THREAD

**Issue by mythros** [jmelosegui/GooglemapMvc#47]
Here is what I found the default user API google keys are mapped to jmelosegui and they're missing from the initialize function _please see below_

-    I would recommend adding `ApiKey(string apiKey)` to the Initialize function below with passing a constructor from web,config
-    The googleAnalytics is using the users GA key, this should also be set here via web.config.

        `private void Initialize()
        {
            //Add google keys here - read from web.config
            ClientEvents = new GoogleMapClientEvents();
            MarkerClientEvents = new MarkerClientEvents();
            DisableDoubleClickZoom = false;
            Draggable = true;
            EnableMarkersClustering = false;
            Latitude = 23;
            Longitude = -82;
            MapTypeId = MapTypes.Roadmap.ToClientSideString();
            MapTypeControlPosition = ControlPosition.TopRight;
            MapTypeControlVisible = true;
            ImageMapTypes = new List<ImageMapType>();
            StyledMapTypes = new List<StyledMapType>();
            Markers = new List<Marker>();
            MarkerClusteringOptions = new MarkerClusteringOptions();
            Polygons = new List<Polygon>();
            Circles = new List<Circle>();
            PanControlPosition = ControlPosition.TopLeft;
            PanControlVisible = true;
            OverviewMapControlVisible = false;
            OverviewMapControlOpened = false;
            StreetViewControlVisible = true;
            StreetViewControlPosition = ControlPosition.TopLeft;
            ZoomControlVisible = true;
            ZoomControlPosition = ControlPosition.TopLeft;
            ZoomControlStyle = ZoomControlStyle.Default;
            ScaleControlVisible = false;
            Height = 0;
            Width = 0;
            UseCurrentPosition = false;
        }`

This is not set or referenced anywhere - 
` public GoogleMapBuilder ApiKey(string apiKey)
        {
            Component.ApiKey = apiKey;
            return this;
        }`

-             Also can you share how are you setting the Apikey now?

**Comment by jmelosegui** [comment]
Hi @mythros, 

**First Point:**

Inside the initialize method of the `GoogleMap` class goes those values I think should be by default or google map api define as default.

Example:

If you go to the [google map api documentation for ZoomControlOptions](https://developers.google.com/maps/documentation/javascript/3.exp/reference#ZoomControlOptions) you will see the default value for ' ZoomControlOptions position` is `TOP_LEFT` 

That is why inside the `initialize` method the GoogleMap Control set that value as default.

```csharp
private void Initialize()
{
     ....  
     ZoomControlPosition = ControlPosition.TopLeft;
     ....
}
```

The `Google Map Api KEY` is not included in those cases and therefore I don't think a default value could be set for that property. 

On the other hand if your want to use the confug file as the place to store your Google Map API Key, the curent implementation is flexible enough to support that feature.

You could create an application configuration setting in you web.config

```xml
 <appSettings>
    <add key="ApiKey" value="{yourapi}" />
 </appSettings>	
```

And then you could pass that value to the control using the ViewModel or any other mechanism (Ex. `ViewBag`, `Session`, etc)

Inside you controller

```csharp
public ActionResult SomeAction(KmlModel model)
{
    var apiKey = ConfigurationManager.AppSettings["ApiKey"];
    return View(apiKey);
}
```

Then in the View

```html
@model System.String

<div style="height: 500px; border: solid 1px #cccccc">
    @(Html.GoogleMap()
          .Name("map")
          .ApiKey(Model))
</div>
```

**Second Point:**

> The googleAnalytics is using the users GA key, this should also be set here via web.config.

Google Analitics doesn't has anything to do with GoogleMap Control for Asp.Net MVC. 

In my project Google Analitics is only used by the Example Project. I dont know why are you refering to that in relation to my control.

**Third Point:**

> This is not set or referenced anywhere 

Yes, it is. Go to the class `GoogleMap` find the method `WriteHtml` you will see how that property is used.

```csharp
protected virtual void WriteHtml(HtmlTextWriter writer)
{
    ...
    var key = (ApiKey.HasValue()) ? "&key=" + ApiKey : String.Empty;
    ...
    var mainJs = String.Format("https://maps.googleapis.com/maps/api/js?v=3.exp{3}{0}{1}{2}", key, languaje, visualization, isAjax);
    ScriptFileNames.Add(mainJs);
	
	...
}
			
```
