### ISSUE TITLE
InfoWindowContent Template Helper

### ISSUE THREAD

**Issue by mythros** [jmelosegui/GooglemapMvc#48]
currently the HTML is just hardcoded in place - i.e. into this variable and rendered in the view `InfoWindowContent = @"<h2>Murcia</h2>",`

Suggestion:
I would like to _suggest_ that we move this into an `@InfoWindowHelper` function with some mechanism to retrieve content from a VM or Model - with some form of modal options / block behind window. Open other modals/close on new open etc.

**Multiple overlays**
When many markers are overlapping, like offices inside a tall building _many markers in same location_ the `InfoWindow` is hard to see with overlapping windows! Do you have a suggestion on how I can resolve this?

**Comment by jmelosegui** [comment]
**InfoWindow**

Could you write down an example of the syntax of the new approach you are suggesting in order to create the InfoWindow?

**Multiple overlays**

Maybe you could try [Markers Clustering](http://www.jmelosegui.com/map/marker/MarkerClustering)
