### ISSUE TITLE
Get coordinates selected in map

### ISSUE THREAD

**Issue by qntapps** [jmelosegui/GooglemapMvc#52]
Hi, firstly congratulations for your job....that's great. I would like use this api and i have save in one repository the location (lat/long) user selected/positioned marker in map. This is possible? If no, do you get any suggestion on how I can implement that? Thank you very much.

**Comment by jmelosegui** [comment]
@qntapps to accomplish what you want, you will need to subscribe to markers client events. 

This [sample](http://www.jmelosegui.com/map/marker/ClientEvents) can show you how and This [answer ](https://github.com/jmelosegui/GooglemapMvc/issues/45#issuecomment-118527837) can give you some insides about your specifics.

Let me know if you need something else.

**Comment by qntapps** [comment]
@jmelosegui, thanks for your response. I'll try your suggestion in this weekend but i think it's just that
i need. I send feedback for you After ...thanks!
