### ISSUE TITLE
centering when binding a list of addresses

### ISSUE THREAD

**Issue by philoushka** [jmelosegui/GooglemapMvc#53]
I've got users who want to map out locations using a list of addresses. 
I've got the addresses all model binding, and it's working really well. :+1: 

How can I have the map _zoomed and centered_ appropriately on the plotted markers when supplying a list of addresses? 

        @{
            Html.GoogleMap()
              .Name("map")
              .Height(500)
              .MarkersGeocoding(true)
              .Center(c => c.Latitude(40).Longitude(-3))  //how can I specify 'auto'?
              .BindTo<RegionInfo, Marker>
              (Model, mappings => mappings.For<RegionInfo>
                  (
                      binding => binding.ItemDataBound
                          (
                              (marker, regionInfo) =>
                              {
                                  marker.Address = regionInfo.Address;
                                  marker.Title = regionInfo.Address;
                                  marker.Window = new InfoWindow(marker)
                                  {
                                      Template =
                                      {
                                            Content = () => ViewContext.Writer.Write(regionInfo.InfoWindowContent)
                                      }
                                  };
                              }
                          )
                  )
              )
              .Render();
        }

        public ActionResult Index()
        {
            IEnumerable<RegionInfo> data = BuildSomeRegions().ToList();
            return View(data);
        }

        private IEnumerable<RegionInfo> BuildSomeRegions()
        {
            yield return new RegionInfo { Address = "Vancouver, BC" };
            yield return new RegionInfo { Address = "New York, NY" };
        }

**Comment by jmelosegui** [comment]
Hi @philoushka 

You need to call the method `FitToMarkersBounds` on the GoogleMap helper.

Please check out this [sample](http://www.jmelosegui.com/map/marker/FitToMarkersBounds) for more info

**Comment by philoushka** [comment]
Big thanks @jmelosegui . That was it. Thanks for helping with this fairly obvious question. I should've looked harder.
