### ISSUE TITLE
client events: notify when marker placed

### ISSUE THREAD

**Issue by philoushka** [jmelosegui/GooglemapMvc#54]
I've got a large number of markers to bind to the map. It works really well, and the map populates as it churns through the list.

Is there a [client event](http://www.jmelosegui.com/map/basic/ClientEvents) or other way that I can hook up a JavaScript method to show the user progress on their large number of markers?

I'd like to show progress or `n/x` have been mapped.

**Comment by jmelosegui** [comment]
Well that question only makes sense if you are using [Geocoding](http://www.jmelosegui.com/map/marker/Geocoding) to load your markers. 

If my assumption is correct, the answer is no......... yet :)

I think I could add a progress event to the markers loading from [Geocoding](http://www.jmelosegui.com/map/marker/Geocoding) but that is not available right now.

So keep tuned. I will try to add that feature.

thank for your feedback

**Comment by jmelosegui** [comment]
Hi @philoushka,

I have implemented this feature. Please review the this [sample](http://localhost/Jmelosegui.Mvc.Googlemap.Examples/marker/Geocoding) and let me know if it fulfill your scenario.

The code for this feature is on dev brach.

**Comment by philoushka** [comment]
Fantastic work, thank you, @jmelosegui !

I'll test locally and update here within the next day or 2.

**Comment by jmelosegui** [comment]
Uppps. Sorry samples were pointing to localhost. 

Just updated the above comment. :)

**Comment by philoushka** [comment]
Thanks again; The sample performs perfectly, and is the exact feature I would use.

I would love to see this feature in the next release of this control.

:+1:
