### ISSUE TITLE
Specifying Google Maps marker colours

### ISSUE THREAD

**Issue by philoushka** [jmelosegui/GooglemapMvc#55]
When you place a marker, the default is Google Maps' red markers?

Is there way, without specifying a local icon, to have Google use your choice of its own colored markers?

http://stackoverflow.com/a/18623391/23199

**Comment by jmelosegui** [comment]
You caught me there. The current version does not allow absolute path when an icon is created. I also realize that the helper method require parameters that should be defaulted in another overload, so if you only want to change the image, you don't have to write the more parameterized method.

So would be nice to write

```
    Html.GoogleMap()
        .Name("map")
        .Height(300)        
        .Markers(marker => marker.Add()
                                .Latitude(23.140971656573335)
                                .Longitude(-82.39435493946075)
                                .Icon("http://maps.google.com/mapfiles/ms/icons/blue-dot.png"))
```

instead of 

```
    Html.GoogleMap()
        .Name("map")
        .Height(300)        
        .Markers(marker => marker.Add()
                                .Latitude(23.140971656573335)
                                .Longitude(-82.39435493946075)
                                .Icon("http://maps.google.com/mapfiles/ms/icons/blue-dot.png", new Size(20, 32), new Point(0, 0), new Point(0, 32))
```

Thanks again for your feedback. I will try to fix it over the weekend.

**Comment by jmelosegui** [comment]
Hi @philoushka,

Now the Icon Helper Method will accept either a virtual or an absolute path. Also I have implemented two more overloads to cover more general use of cases (IMHO). You can find more info in the following [sample](http://localhost/Jmelosegui.Mvc.Googlemap.Examples/marker/CustomIcons).

**Comment by philoushka** [comment]
Fantastic, thanks @jmelosegui !

I will use your example with the Google color-dot.png.

Would you consider building a new method like:

**Comment by jmelosegui** [comment]
@philoushka I do am open to contributions, but in this case by creating the helper you are proposing the control should include and distribute the images related with the different markers colors or, as you said in your comment, assume:

> that Google doesn't change their marker images - file name, colour, or size

On the other hand I don't see to much benefit comparing this

```csharp
marker.Add()
    .GoogleIcon("blue")
```
with 
```csharp
marker.Add()
      .Icon("http://maps.google.com/mapfiles/ms/icons/blue-dot.png"))
```
However, I am really glad about your suggestion. It made me realize that a developer could want to extend the control with a custom method.

I just committed the code related with the issue #56.

with [that code](https://github.com/jmelosegui/GooglemapMvc/commit/8685da3e22760093227acdeadc13bf772d349b58) _(currently on dev branch)_ you could create your extension like the following.

```csharp
public static class HtmlHelperExtension
{
    public static MyGoogleMapBuilder MyGoogleMap(this HtmlHelper helper)
    {
        if (helper == null) throw new ArgumentNullException("helper");

        return new MyGoogleMapBuilder(helper.ViewContext);
    }
}

public class MyGoogleMapBuilder : GoogleMapBuilder
{
    public MyGoogleMapBuilder(ViewContext viewContext) : base(viewContext) { }

    public MyGoogleMapBuilder Markers(Action<MyMarkerFactory> action)
    {
        if (action == null)
            throw new ArgumentNullException("action");
        MyMarkerFactory markerFactory = new MyMarkerFactory(Component);
        action(markerFactory);
        return this;
    }
}

public class MyMarkerFactory : MarkerFactory
{
    public MyMarkerFactory(GoogleMap map) : base(map) { }

    public new MyMarkerBuilder Add()
    {
        MarkerBuilder builder = base.Add();
        return new MyMarkerBuilder(builder);
    }
}

public class MyMarkerBuilder : MarkerBuilder
{
    public MyMarkerBuilder(MarkerBuilder builder) : base(builder) { }

    public MyMarkerBuilder GoogleIcon(string color)
    {
        //TODO: To figure out the path base on the color
        string path = "http://maps.google.com/mapfiles/ms/icons/blue-dot.png"; 
        base.Icon(path);
        return this;
    }
}
```
and then use **and reuse** your method in the way you proposed _(Notice the order in the method chain)_
```csharp
@(
 Html.MyGoogleMap()
            .Markers(m => m.Add()
                        .GoogleIcon("blue")
                        .Title("Hello World!"))
            .Name("map")
            .Height(500)
)
```
I would like to know you opinion on this.
And again, thanks for your feedback.

**Comment by philoushka** [comment]
Thanks for the thought and consideration on this. If not in the GoogleMapMvc library, but as an extension method, I can definitely get behind that. Bonus if you would ship that in the NuGet package and create the HtmlHelperExtension for your package users.

Myself I'd only change to use https, and a simple string interpolation if you can get away with shipping with C# 6.

    public MyMarkerBuilder GoogleIcon(string color)
    {
        base.Icon($"https://maps.google.com/mapfiles/ms/icons/{color}-dot.png");
//        base.Icon(string.Format("https://maps.google.com/mapfiles/ms/icons/{0}-dot.png",color));
        return this;
    }

Thanks for being open to the suggestion, and I hope you can ship this extension method in the NuGet package.It'd definitely help keep code DRY.

**Comment by rparrella** [comment]
Hello,

When using "custom icons" for the markers, I notice that the icon does not stay anchored to the correct lat/lon when the map is zoomed in or out.

For example, this does not seem to behave properly (blue google dot):

marker.Icon = new MarkerImage("http://maps.google.com/mapfiles/ms/icons/blue-dot.png", new Size(32, 32), new Point(0, 0), new Point(0, 32));

If I remove the previous line of code, I get the default red google dot and it anchors correctly when zooming the map.

Thanks

**Comment by rparrella** [comment]
Hello, when adding a custom marker, such as...
marker.Add()
                .Latitude(23d)
                .Longitude(-82.3d)
                .Title("Hello World!")
                .Icon("~/Images/beachflag.png", size , origin, anchor)
                .Draggable(true);

It seems to automatically resolve to:
"path":"http://www.jmelosegui.com/map/Images/beachflag.png"

Is there any way to force the path to stay relative? In my environment, custom markers seem to resolve to the "internal" ip address of my app server. (perhaps because my app server is behind a load balancer). In  this case my custom icons resolve to:

 "path":"http:/10.x.x.x/map/Images/beachflag.png", which is not accessible via Internet, and thus my custom markers do not display.

Thanks, and my compliments on Jmelosegui.Mvc.GoogleMap

**Comment by jmelosegui** [comment]
Hi @rparrella,

Thanks for your feedback. I just opened a new issue #79 to keep tracking of your request. Please refer to that issue to know its status.
