### ISSUE TITLE
Outlining city limits

### ISSUE THREAD

**Issue by philoushka** [jmelosegui/GooglemapMvc#57]
Does Google provide this feature in its API as well?

Search for a city via geocode, and have its boundaries highlighted?

If so, are you interested in adding this feature to GooglemapMvc? Please forgive me if this is already in this library and I've missed it.

![image](https://cloud.githubusercontent.com/assets/930731/8894401/9a26eeee-336a-11e5-8bd0-9c8fd10fd2b7.png)

**Comment by jmelosegui** [comment]
That would be a nice feature to have. But I don't know if it is already in the google map api. Yes, I would like to add it to this library.

Are you offering yourself to implement it? :)

**Comment by philoushka** [comment]
[It appears the API isn't available right now](http://stackoverflow.com/questions/31639198/). That commenter appears quite knowledgeable, so perhaps this won't be a viable change for this library.

**Comment by jmelosegui** [comment]
OK, Meanwhile I will close this issue. We can come back whenever the feature become available within the google map api.
