### ISSUE TITLE
Map loading a big gray screen

### ISSUE THREAD

**Issue by jbravobr** [jmelosegui/GooglemapMvc#58]
Hi!
First of all, let me give you a huge congrats!! This is the most amazing component !
Maybe you could help me with my issue. Using the control at my development environment the control works fine. But When I consume my server (after deploy the application) when I'm trying to render the map using the radius circle area the map shows the Zoom in/ou control, the buttons for Satellite or hybrid view bu the big area for the map display all gray.
Any ideas ?
Cheers!

**Comment by jmelosegui** [comment]
Hi @jbravobr 

Can you post a simplified portion of code that reproduces the error? (The less code the better) 
Maybe you could share a link to the page having the error?

Thanks for your feedback.

**Comment by jbravobr** [comment]
Hi Juan

It's revealed that the problem was with my controller and the parse of lat
and long with values using comma as decimal separator. Change it to a dot
works!

Thanks!!

Em ter, 28 de jul de 2015 às 22:33, Juan Manuel Elosegui <
notifications@github.com> escreveu:
