### ISSUE TITLE
Get long lat from geocoded 

### ISSUE THREAD

**Issue by philoushka** [jmelosegui/GooglemapMvc#61]
I have a use case where users will be entering addresses to plot on a map. Sometimes these are in the hundreds. 

Is there an existing function to take the result of the geocoded lookup and use its long and lat for future use?

I'm under the assumption that lat long plots are cheaper/faster than geocode lookups.

**Comment by jmelosegui** [comment]
Hi @philoushka,

There is no such feature rigth now in the control, but I am not too far from it. 

Currently you can subscribe to the "markers geocoding completed" event and I am able to pass the marker collection as an argument to any handler of that event. that marker collection use as index the marker identifier mapped when databinding (see [this sample](http://www.jmelosegui.com/map/marker/ExternalReference)  description for more info). Every marker in that collection also has the location (lat, lng). 

So to fulfill your request I will add the address used to obtain each marker location to the corresponding marker in the collection passed as arguments. 

From this point on the rest is all yours. You will need to subscribe to the "markers geocoding completed" event and pass the marker collection to some service in you application to process and save that information, so the next time a user request a location from a known address you will be able to return the location bypassing the geocoding.

Let me know if this sound right to you.

**Comment by philoushka** [comment]
Thanks @jmelosegui , that would be fantastic.

I've gotten close by `OnMarkersGeocodingProgress`, but if you're able to offer a concrete more reliable method, I'd be very much appreciative of that feature.

**Comment by jmelosegui** [comment]
Hi @philoushka,

Just committed a change to add the address information to any geocoded marker.
the following image show the address information when inspecting a marker.

![image](https://cloud.githubusercontent.com/assets/450246/9701118/45dcc854-53ea-11e5-9b7f-f482cb137221.png)

The code is on dev branch, but I am planning to release a new versio sometime in the next 2 days.

Again thanks for your feedback.
