### ISSUE TITLE
Correct way to grab GMap reference?

### ISSUE THREAD

**Issue by Workings** [jmelosegui/GooglemapMvc#63]
Whats the correct way to grab a reference to the Google map instance? Wanting to do additional things on the client side for adding polys etc, but not sure how should be getting ($jmelosegui.Googlemap.prototype.GMap)?

**Comment by jmelosegui** [comment]
Please see the issue #13 or refer to [this](http://www.jmelosegui.com/map/basic/ClientEvents) sample.

Feel free to ask any further question.

**Comment by Workings** [comment]
Thanks for that and very speedy response!
