### ISSUE TITLE
Multiple requests via AJAX, multiple scripts registered via Html.GoogleMap().ScriptRegistrar()

### ISSUE THREAD

**Issue by rafaelfracasso** [jmelosegui/GooglemapMvc#64]
Example:  http://www.jmelosegui.com/map/basic/AjaxPartialView 
![jmelo](https://cloud.githubusercontent.com/assets/1108788/9450155/04067584-4a75-11e5-9e6b-8a37f41f4afb.png)

If there is multiple requests (like clicking several times on the "Load" button), are registered in the <head> multiple scripts "https://maps.gstatic.com/maps-api-v3/api/* ". and with that, a console error: "You have included the Google Maps API multiple times on this page. This may cause unexpected errors."

I'm using a work around to remove all maps.gstatic from the <head> (and also the style tags), but its better if the Html.GoogleMap().ScriptRegistrar() check before includes it

**Comment by jmelosegui** [comment]
Hi @rafaelfracasso.

I am afraid the `ScriptRegistrar` cannot check whether those scripts are included in the client or not. 
The  `ScriptRegistrar` render process happens on server side per request and I have no easy way to determine whether a request is from a client who doesn't have the google map script registered (first ajax request) or not (subsequent request on the same page). Is the client the only one who knows if those scripts are already present.

Right now I can see any but a hacky way to workaround this issue, but that is something you've already done ;), so let me think more about it and as soon as I get something I'll come back and let you know.

Thanks for your feedback!!!!

**Comment by jmelosegui** [comment]
Hi @rafaelfracasso 

Just committed a change to fix this issue. Please see all the information and the complete implementation [here](http://www.jmelosegui.com/map/basic/AjaxPartialView).

Changes are on dev branch. I am planing to release a new version some time in next 2 days.

Thanks again for your feedback
