### ISSUE TITLE
Placing a Marker Inside / on-top-of a Polygon/ Shape (still having access to long, latt, ...etc.)

### ISSUE THREAD

**Issue by aidanrsa** [jmelosegui/GooglemapMvc#65]
Hi Juan,

Great work - found this to be a great way to easily use google maps in ASP.NET MVC.

I've been unable to place a marker inside a created polygon on the map. I am able to add a marker anywhere outside the polygon.

I've tried setting clickable to true and false for the polygon property. I assumed clickable(false) would refer to ignoring the click on the polygon and instead on the map object?

Many thanks in advance.

![image](https://cloud.githubusercontent.com/assets/14042844/9568466/592b2418-4f4a-11e5-87de-1707307d400d.png)

**Comment by jmelosegui** [comment]
Hi @aidanrsa,

You just found a bug. 

I will commit a fix for that. Though I wont be able to release a new version of the control util I finish other things I am working on.

**Comment by jmelosegui** [comment]
Hi again @aidanrsa,
 
I just committed a change that should fix the bug. The change is on dev branch. If you have a chance to try it, please let me know if that solve your issue.

Thanks for your feedback !!!!!

**Comment by aidanrsa** [comment]
Hi Juan,

Thanks very much. I'll download dev branch and give it a test. 

I'll update the nuget package in my project when you are ready to release it - any ideas on a rough date for nuget update i.e a week / months time . 

Thanks for a great project demo and code!

**Comment by jmelosegui** [comment]
I am planing to release a new version some time in next 2 days.
