### ISSUE TITLE
ssl

### ISSUE THREAD

**Issue by s4054378** [jmelosegui/GooglemapMvc#67]
Just wondering if there could be a way to use this with ssl.

when chrome loads the googlemap it turns off the green padlock - stating there is something unsecured on the page and all I have is googlemap

**Comment by jmelosegui** [comment]
Hi @s4054378, 

I just setup the web site sample project to use IISExpress under ssl, and as you can see in the following image I did have no problem whatsoever, rendering the map over ssl.

Please can you provide more info about your environment?

![image](https://cloud.githubusercontent.com/assets/450246/9696219/335880e8-533a-11e5-8045-32cc8087c706.png)

**Comment by s4054378** [comment]
Hey Juan

My site isnt completely live yet.

My ssl is fine for all the pages except my locations page. as per the
pictures below.

The only thing I have on the locations page that is different to other
pages is below.

cshtml before compile.

@using System.Drawing;
@using Jmelosegui.Mvc.Googlemap
@using Jmelosegui.Mvc.Googlemap.Overlays
@model IEnumerable<WebApplication1.Models.LocationCord>

@{
    ViewBag.Title = "First Look";
}
@section scripts
{
    @(Html.GoogleMap().ScriptRegistrar())
<script type="text/javascript">
    $(function () {
        var width = (window.innerWidth > 0) ? window.innerWidth :
screen.width;
        })
    }
</script>
}

@{
    Html.GoogleMap()
                .Name("map")
                .Width((int)ViewData["width"])
                .Height((int)ViewData["height"])
                .Center(c =>
c.Latitude((double)ViewData["latitude"]).Longitude((double)ViewData["Longitude"]))
                .Zoom((int)ViewData["zoom"])
                .EnableMarkersClustering(options =>
                {
                    options.MaxZoom = (int)ViewData["MaxZoom"];
                    options.GridSize = (int)ViewData["GridSize"];
                    options.AverageCenter = (bool)ViewData["AverageCenter"];
                    options.ZoomOnClick = (bool)ViewData["ZoomOnClick"];
                    options.HideSingleGroupMarker =
(bool)ViewData["HideSingleGroupMarker"];
                    if ((string)ViewData["CustomStyles"] == "StackOverflow")
                    {
                        options.CustomStyles.Add(new MarkerClusteringStyles
                        {
                            Url = "~/Resources/Images/clust1.png",
                            Height
                                = 75,
                            Width = 75,
                            TextSize = 20,
                            TextColor = Color.Black

                        });
                        options.CustomStyles.Add(new MarkerClusteringStyles
                        {
                            Url = "~/Resources/Images/cluster2.png",
                            Height
                                = 45,
                            Width = 45,
                            TextSize = 12,
                            TextColor = Color.Black
                        });
                        //  options.CustomStyles.Add(new
MarkerClusteringStyles
                        //  {
                        //       Url = "~/Resources/Images/cluster3.png",
                        //       Height
                        //           = 100,
                        //        Width = 100,
                        //        TextSize = 20,
                        //        TextColor = Color.Black
                        //    });
                    }
                })
                .BindTo<WebApplication1.Models.LocationCord, Marker>
                (Model, mappings =>
mappings.For<WebApplication1.Models.LocationCord>
                        (
                            binding => binding.ItemDataBound
                            (
                                (marker, obj) =>
                                {
                                    marker.Latitude =
Convert.ToDouble(obj.Lat);
                                    marker.Longitude =
Convert.ToDouble(obj.Long);
                                }
                            )
                        )
                )
                .BindTo<WebApplication1.Models.LocationCord, Circle>
                (Model, mappings =>
mappings.For<WebApplication1.Models.LocationCord>
                        (
                    binding => binding.ItemDataBound
                            (
                                (circle, obj) =>
                                {
                                    circle.Center = new
Location(Convert.ToDouble(obj.Lat), Convert.ToDouble(obj.Long));
                                    circle.Radius =
Convert.ToInt32(obj.Radius);

                                }
                            )
                            ))
                .Render();
}


and page source

<div class="googlemap" id="map" style="height:100%"></div>

//<![CDATA[ jQuery(document).ready(function(){
jQuery('#map').GoogleMap({clientId:'map', enableMarkersClustering:true,
height:0,
center:{"latitude":-25.626092,"longitude":133.665346,"useCurrentPosition":false},
mapTypeId:'ROADMAP', zoom:4,
markerClusteringOptions:{"maxZoom":16,"gridSize":45,"averageCenter":true,"hideSingleGroupMarker":true},
markers:[{"lat":-20.266893,"lng":148.716935},{"lat":-20.269776,"lng":148.715665},{"lat":-20.267385,"lng":148.71775}],
markerEvents:{},
circles:[{"fillColor":"#FF0000","fillOpacity":0.5,"strokeColor":"#8B0000","strokeOpacity":0.8,"strokeWeight":2,"center":{"latitude":-20.266893,"longitude":148.716935},"radius":100},{"fillColor":"#FF0000","fillOpacity":0.5,"strokeColor":"#8B0000","strokeOpacity":0.8,"strokeWeight":2,"center":{"latitude":-20.269776,"longitude":148.715665},"radius":100},{"fillColor":"#FF0000","fillOpacity":0.5,"strokeColor":"#8B0000","strokeOpacity":0.8,"strokeWeight":2,"center":{"latitude":-20.267385,"longitude":148.71775},"radius":70}]});
}); //]]>


Its not a deal breaker but it would be nice to have the green padlock on
all the pages.

Thanks Dale

**Comment by jmelosegui** [comment]
To narrow down that issue, I will suggest to start with a simple map, something like this.

```
@(
     Html.GoogleMap()
         .Name("map")
         .Height(500)
   )
```
That map should be rendered over both: http and https. Let me know if not.
