### ISSUE TITLE
Draw line

### ISSUE THREAD

**Issue by fivitti** [jmelosegui/GooglemapMvc#69]
Hi!
Is possible draw a track on map? I can draw a KML track, but I want set list of points in code.
I can draw a polygon - closed curve, but I cannot draw a line - open curve.

**Comment by jmelosegui** [comment]
Hi @fivitti 

I just committed a set of changes to allow drawing [Google Polylines](https://developers.google.com/maps/documentation/javascript/examples/polyline-simple) over the map through the control.
You can see a working sample [here](http://www.jmelosegui.com/map/Shapes/PolylineBasic).

Please review the sample and let me know if that fulfill your request.

*The changes are on the dev branch.*

Thanks for your feefback.

**Comment by fivitti** [comment]
Hi!
Great! This is it!
Very, very thanks for your work. Your project is really useful. ;)
