### ISSUE TITLE
Visual Studio 2015 error

### ISSUE THREAD

**Issue by maxitimes** [jmelosegui/GooglemapMvc#70]
Followed the instructions, created new MVC project, install-package, added code as per instructions, built project with no errors, F5 or run in Microsoft Edge

Got the attached error.

Compiler Error Message: CS1061: 'HtmlHelper<dynamic>' does not contain a definition for 'GoogleMap' and no extension method 'GoogleMap' accepting a first argument of type 'HtmlHelper<dynamic>' could be found (are you missing a using directive or an assembly reference?)

Thank you

![jmelosegui comerror](https://cloud.githubusercontent.com/assets/13531192/9807687/f5430250-5899-11e5-86cd-36df7cc70fcb.JPG)

**Comment by jmelosegui** [comment]
@maxitimes 

I am sorry about that. The install instruction should be explicit about adding the required namespace.
So please add the following using to the very top of your page:
```
@using Jmelosegui.Mvc.GoogleMap
```
and your map sould be rendered. 

Please let me know if you have any other problem.

Thanks for your feedback

**Comment by maxitimes** [comment]
Thanks for your help, all working well

Hope to launch an app soon with your mapping feature.  I am looking to
utilize the searching feature in your Services Geolocation example.  I just
need to work out how to get
the Lat / Long coordinates of the search as well to do what i want with it.

What do you hope to achieve with your Google Map MVC Package?  If you need
me to like it or provide positive feedback let me know

Thanks

**Comment by jmelosegui** [comment]
@maxitimes I do expect nothing especial. This is a "code for fun" project.

Thank, again for your feedback.

**Comment by maxitimes** [comment]
Hi Juan

Thanks again for your help with using your map package.

I have been able to create an app which uses your map and have released it
here
www.envygo.com.au

The issue i am having is working out how to get the map to update daily
with a new location to display.  I can get the location i am after from the
database but don't seem to be able to
pull this string out of the model data to display.

You can see what i am trying to achieve on the home page of the app.  I
have hard coded "Australia, Canberra" and can get this to display but i
really want to show the country / city out of the database in the code below

My Controller
        public ActionResult Index()
        {
            var IndexDayOfYear = (System.DateTime.Today.DayOfYear);

            ViewBag.DayOfYearMessage = IndexDayOfYear;
            ViewBag.Message = "Australia, Canberra";

            var IndexLocations = from x in db.IndexLocations
                                 select x;
            IndexLocations = IndexLocations.Where(x =>
x.ID.Equals(IndexDayOfYear));

            return View(IndexLocations.ToList());
        }


My View
@using Jmelosegui.Mvc.GoogleMap
@model IEnumerable<WebDBTest.Models.IndexLocations>


@{
    ViewBag.Title = "Home Page";
}

<h2>@ViewBag.Message.</h2>

<div class="row">
    <div class="col-md-12">
        @(Html.GoogleMap()
              .Name("map")
              .Height(500)
              .Center(c => c.Address(@ViewBag.Message))
              .Markers(m => m.Add().Title("I am Live"))

        )
    </div>
</div>

<table class="table">
    <tr>
        <th>
            <a>Day Id</a>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Country)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.City)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
        </tr>
    }
</table>

As you may have guessed i am new to MVC and need a little help

Also if your interested, i am keen to find / pay a enthusiast to help me
add some features to the app.  Currently in the menu item "MyLink" you will
see i am trying to link users that have registered.  So if you are a
current user, you want to be able to search for a friend and add them as a
friend, then the users show in the table as indicated as friends or
connections.

I can give access via RDP to my visual studio and pay with paypal.  Just
provide me a price and we can talk about it.

Thank you
