### ISSUE TITLE
Printing (ctrl+p) of the control/map doesnt seem to work

### ISSUE THREAD

**Issue by des2k7** [jmelosegui/GooglemapMvc#74]
It seems like the map is not printable. I've spent several hours trying to find out why and can't find it.
The map stays blank/gray but the markers do show up.
The clusters are printable (with image) if you use MarkerClustererPlus for Google Maps V3

It seems that the "vanilla" gmaps3 version does work. Both my implementation and yours (the demo site) dont show up in the print preview for chrome and firefox.

I am not 100% certain the issue is with your wrapper as you dont really apply CSS of some kind.

If you have any idea: it would be greatly appreciated :-)

**Comment by des2k7** [comment]
the problem seemed to be bootstrap (using 3.3.2).
Some css selector was setting max-width: 100% !important on images in its @media print

Overriding this on my print css solved my problem:
```css
#map img {      
        max-width: none !important;
    }
```

So the problem is not really with your component, but with bootstrap.

**Comment by jmelosegui** [comment]
Hi @des2k7,

Thank you very much for your feedback!!!!
