### ISSUE TITLE
Bind to Map (Markers) shows Info Window Contents as normal page text.

### ISSUE THREAD

**Issue by lordofscripts** [jmelosegui/GooglemapMvc#85]
I followed your example about binding to a model for markers (see my other post for details about how I did it) and each of my two markers has an info window text.

I noticed that when the map is rendered, the Title property is rendered as tooltip (as I have seen happen) and that is okay, but the actual Info Window Text (info window content) is displayed above the map as if I had put it there as normal page content. It is not displayed as Info Window Text. When I click on the marker an empty Info Window is popped up because the text is rendered elsewhere in the page.

Is there something missing from the example? for example I have noticed that your examples use the zIndex property when in reality the code expects ZIndex (uppercase Z) instead.

**Comment by jmelosegui** [comment]
Yes, that is a documentation typo. 

I will suggest you to always review the `View` and `Controller` tabs. In those tabs you will see the actual code used to run any specific sample.

**Comment by lordofscripts** [comment]
Yup, that's what I have been doing after I noticed that. But the issue described in this post happens using the code in the View, not the code in the Documentation tab.

**Comment by jmelosegui** [comment]
could you post any sample code (the less the better) reproducing the issue??

**Comment by lordofscripts** [comment]
As I mentioned earlier RegionInfo is like the one in your Examples\App_Data, PathInfo is basiocally a RegionInfo with only Latitude/Longitude (for path vertices) and ExtendedRegionInfo is a model that has two List<> properties, one for RegionInfo and the other for PathInfo because I need to display both in the same map.

@using Jmelosegui.Mvc.GoogleMap
@model Models.ExtendedRegionInfo


@(Html.GoogleMap().Name("map").Height(500)
                  .Center(c => c.Latitude(@ViewBag.Lat)
                                .Longitude(@ViewBag.Lon)
                         )
                  .BindTo<Models.RegionInfo, Marker>
                  (Model.Regions, mappings => mappings.For<Models.RegionInfo>
                    (
                        binding => binding.ItemDataBound
                            (
                                (marker, regionInfo) =>
                                {
                                    marker.Latitude = regionInfo.Latitude;
                                    marker.Longitude = regionInfo.Longitude;
                                    marker.Title = regionInfo.Title;
                                    marker.ZIndex = regionInfo.ZIndex;
                                    marker.Icon = new MarkerImage(String.Format("~/Images/MapIcons/{0}", regionInfo.ImagePath)
                                        , new System.Drawing.Size(32, 37)
                                        , new System.Drawing.Point(0, 0)
                                        , new System.Drawing.Point(15, 35));
                                    marker.Window = new InfoWindow(marker)
                                    {
                                        Template =
                                        {
                                            Content = () => ViewContext.Writer.Write(regionInfo.InfoWindowContent)
                                        }
                                    };
                                }
                            )
                    )
                )

                .BindTo<Models.PathInfo, Circle>
                (Model.Paths, mappings => mappings.For<Models.PathInfo>
                    (
                        binding => binding.ItemDataBound
                        (
                            (circle, obj) =>
                            {
                                circle.Center = new Location(obj.Latitude, obj.Longitude);
                                circle.Radius = (int)250 / 50;
                            }
                        )
                    )
                )

                .BindTo<Models.PathInfo, Polyline>
                (Model.Paths, mappings => mappings.For<Models.PathInfo>
                    (
                        binding => binding.ItemDataBound
                        (
                            (poly, obj) => poly.AddPoint(new Location(obj.Latitude, obj.Longitude))
                        )
                    )
                )

                  .Zoom(15)
                  .Markers(marker => marker.Add()
                    .Title(@ViewBag.PlaceName as string)
                    .Window(window => window.Add()
                            .MaxWidth(200)
                            .ZIndex(3)
                            .DisableAutoPan(false)
                            .Content(
                                @<text>
                                <div><h5>@ViewBag.PlaceName</h5><p> texto texto </p> </div >
                                </text>
                            )
                      )
                  )

 )


@section scripts
{
    @(Html.GoogleMap().ScriptRegistrar())    
}

**Comment by lordofscripts** [comment]
Any news? still having a problem with this issue. The content of the info window appears just above the Map DIV as if they were regular text. The do not appear as content of the marker's info window

**Comment by jmelosegui** [comment]
Could you create a simple project here on github reproducing that issue?? If so I could look at it and try  to figure out the issue (if there is one).

**Comment by jmelosegui** [comment]
Something new on this??
