### ISSUE TITLE
Printing Maps Not Working

### ISSUE THREAD

**Issue by khalome** [jmelosegui/GooglemapMvc#89]
I noticed today that when trying to print maps the map will not display in the print preview. Markers, icons etc will still appear but no map. This occurs on my website and the authors site as well. For example: try to print this page http://www.jmelosegui.com/map/marker/SimpleMarker. No map as of right now. Any ideas?

**Comment by jmelosegui** [comment]
There is a detailed workaround [here].(https://github.com/jmelosegui/GooglemapMvc/issues/74#issuecomment-147381908)

Please let me know if that helps.
