### ISSUE TITLE
Disable zooming with mouse wheel

### ISSUE THREAD

**Issue by YoanX1** [jmelosegui/GooglemapMvc#90]
Hi,

is there a functionality for disabling the zoom performed wtih the mouse wheel? If not, you can consider this as a feature request :)

p.s. I think that DisableScrollWhellZoom() or  ScrollWheel=False are good options.

**Comment by jmelosegui** [comment]
Hi YoanX1,

That feature is not available in the control, but is a simple one to implement. I would rather do something like:

```csharp
@(Html.GoogleMap()
          .Name("map")
          .ScrollWheel(false))
```
to keep discoverability of this control consistent with the [google map api](https://developers.google.com/maps/documentation/javascript/reference?csw=1#MapOptions) _(and the ScrollWheel value should be true by default)_

So if you feel confident enough with this one I'll be willing to review and accept your pull request :)

Thanks for your feed back.

**Comment by YoanX1** [comment]
Hi,

I do not have a pull request, but I agree about the name of the property. It should be consistent with the official api.

**Comment by jmelosegui** [comment]
Hi @YoanX1,

Just pushed a change that should resolve your request. 

If you need to see the feature live, go [here](http://www.jmelosegui.com/map/basic/UIControls) and change the `Scroll Wheel` value to see this in action.

Also take a look to the following link, that could be helpful if you need to use this feature right away.

https://github.com/jmelosegui/GooglemapMvc#links.

**Comment by jhallam3** [comment]
Hi, trying this now and still doesn't work .. Im using 0.8.0

![screen shot 2016-08-06 at 13 45 09](https://cloud.githubusercontent.com/assets/5174328/17456824/04a384d6-5bdc-11e6-9e77-736380866b6a.png)
