### ISSUE TITLE
Bug: Javascript error when geolocation service not avaliable

### ISSUE THREAD

**Issue by gcapnias** [jmelosegui/GooglemapMvc#92]
Steps to replicate in Chrome: Developer tools, Sensors, emulate position unavailable.

The map comes with the error:
- Error: The Geolocation service failed.
which is ok, but then an exception is thrown:

- Uncaught TypeError: Cannot read property 'latitude' of undefined(anonymous function) @ VM1108 jmelosegui.googlemap.js:813

Original line 
- self.load(new google.maps.LatLng(this.latitude, this.longitude));
 should be changed to 

- self.load(new google.maps.LatLng(this.center.latitude, this.center.longitude));

I think this bug exists in more cases - there are other parts of map initialization, than use the same attributes, which are wrong.

**Comment by jmelosegui** [comment]
Good catch. I am now fixing this. Sorry for the late response, though.

**Comment by afzalgujrat** [comment]
I've using Nuget 0.8.0.0 and this issue is still there any ideas ?

**Comment by jmelosegui** [comment]
hi @afzalgujrat, 

I will release a new version of the package soon. Meantime you could follow [this](https://github.com/jmelosegui/GooglemapMvc#self-service-releases) instructions to get the latest version from the CI server.
