### ISSUE TITLE
I can not use Polyline in my vs 2015

### ISSUE THREAD

**Issue by behibehibehi** [jmelosegui/GooglemapMvc#94]
Hello do not bother,i'm download google map control and work correct,but when i want use the Polyline,i get this error:
"MapBuilder " does not defination for "Polyline" are you missing assembly refrenece?
what happen?i use this link for that purpose:
[](http://www.jmelosegui.com/map/Shapes/PolylineBasic)

**Comment by jmelosegui** [comment]
Do you have any sample code reproducing that error?
Did you follow the steps in  [this sample](http://www.jmelosegui.com/map/Shapes/PolylineBasic)?

**Comment by behibehibehi** [comment]
Yes I'm follow that step,but vs 2015 under of Polyline draw line and saye :
"MapBuilder " does not defination for "Polyline" are you missing assembly refrenece?

**Comment by fmejiap** [comment]
Hi,
I have the same problem, cannot resolve Polylines.

If you visualize with Assembly Explorer no exist Polyline.

See you.

**Comment by jmelosegui** [comment]
I would like to know the version you have installed?

**Comment by fmejiap** [comment]
Hello jmelosegui.

I have installed the last version 0.8.0.0. The same issue  with 0.7.0.1.

I'm following the [example ](http://www.jmelosegui.com/map/Shapes/PolylineBasic) with VS 2013 and VS 2015.I can not attach a sample file that exceeds 10 MB.

Thanks.

**Comment by ubfacility** [comment]
i am having the same...issue....as fmejiap....

**Comment by jmelosegui** [comment]
The correct version to use Polyline feature is:

[https://www.nuget.org/packages/Jmelosegui.Mvc.Googlemap/0.8.16-beta-gd2b2689432](https://www.nuget.org/packages/Jmelosegui.Mvc.Googlemap/0.8.16-beta-gd2b2689432)
