### ISSUE TITLE
Only one marker on mouse click

### ISSUE THREAD

**Issue by eduseixas** [jmelosegui/GooglemapMvc#96]
- How to stay only one marker on click event on the map?
By clicking again on the map, the previous marker is deleted.

**Comment by jmelosegui** [comment]
I think I cannot complete understand you issue.
Do you have any sample code?
Can you provide step to reproduce the error?

**Comment by eduseixas** [comment]
Grateful for fast contact.. Its a question. this is not a error.
I need create a marker on mouse click event (it´s ok!), but if exists a previus marker in the map, this to be deleted automatically, leaving only the last marker on the map.
How can I do this?

**Comment by eduseixas** [comment]
Resolved: [http://stackoverflow.com/questions/1544739/google-maps-api-v3-how-to-remove-all-markers](url)

**Comment by jmelosegui** [comment]
Thanks for your feedback
